### PR TITLE
Publish Set-SPOSiteScript

### PR DESCRIPTION
**Pull request by Linda-Editor**
Please merge the copy in my fork to master and then to live.

sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteScript.md

### CODE REVIEW

**Comment by Linda-Editor** [comment]
Added 5 new topics; please hold off on merging to MicrosoftDocs master (I didn't realize they'd attach themselves to this pull request)

**Comment by Linda-Editor** [comment]
This is ready to be merged to master and live. Go for it. Thanks!

**Comment by Linda-Editor** [comment]
@kenwith Hi Ken, could you merge this pull request and push these docs live? Thanks...

**Comment by kenwith** [comment]
@VesaJuvonen owns the SPO docset and can merge.

**Pull request merged**
