### PR TITLE
Removing any reference of Conference ID reset from the page

### PR DESCRIPTION
**Pull request by Mshaikh-msft**
Removing any reference of Conference ID reset from the page since it's no longer supported.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]
I'm ok after @get-itips suggestion.

**Comment by yogkumgit** [comment]
@Mshaikh-msft Please implement the suggested changes. Thanks

**Comment by Mshaikh-msft** [comment]
> @Mshaikh-msft Please implement the suggested changes. Thanks

Done

**Comment by yogkumgit** [comment]
@get-itips @tseward

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
