### PR TITLE
Update Export-PnPTaxonomy.md

### PR DESCRIPTION
**Pull request by JarbasHorst**
Replaced TermSet with TermSetId in examples 3 and 4.

Fixes: #4690

### CODE REVIEW

**Comment by kenwith** [comment]
@JarbasHorst  - thank you for the PR. The PnP cmdlet references are a little different than the rest of the Office cmdlet references. The PnP 'source' for the reference actually lives in the cmdlet code itself and each release the PnP maintainers generate the references from code and then copy the markdown over to this location so it is rendered alongside the rest of the Office cmdlet references. I will go ahead and merge this here but it will get overwritten the next time the PnP maintainers generate cmdlet reference from the cmdlet code unless it is also updated in the source for the cmdlet itself.

I believe the source file for this particular cmdlet is located here: https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Taxonomy/ExportTaxonomy.cs

The repo is community driven and maintained and I know they would very much appreciate your contribution.

**Comment by JarbasHorst** [comment]
Hello @kenwith , 
thanks for your feedback. I will have a look at that PnP source file!

**Comment by JarbasHorst** [comment]
@kenwith just to let you know, I've created a PR which fixes the PnP source file 😀

**Comment by kenwith** [comment]
Awesome!

**Pull request merged**
