### PR TITLE
Adding missing params

### PR DESCRIPTION
**Pull request by get-itips**
Still work in progress

https://github.com/MicrosoftDocs/office-docs-powershell/issues/7593

### CODE REVIEW

**Comment by get-itips** [comment]
@dariomws what are your thoughts on ChannelUserObjectId? I configured a CQ to land on a channel using the TAC but that did not ask me for that parameter...

**Comment by dariomws** [comment]
How did you test it? I tried, and it says it's a mandatory parameter:
image

But I have no idea about it...

**Comment by get-itips** [comment]
> How did you test it? I tried, and it says it's a mandatory parameter:
> image
> 
> But I have no idea about it...

Yes, using Ps says it's mandatory, but this was not asked in the TAC (at least to plain sight)

**Comment by dariomws** [comment]
Yes, I agree. I also tested on TAC and chose the channel was enough. Also, the Get cmdlet doesn't show it.

**Comment by get-itips** [comment]
I think that if we do not get more info than this, it is better than nothing, so marking ready for review.

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward Please review

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Comment by garycentric** [comment]
I removed the hyphens from "Example 1" and "Example 2", two third-level headings, because of how it looks on docs.microsoft.com.

image

**Pull request merged**
