### PR TITLE
added filter example

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/7989

### CODE REVIEW

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Comment by traya1** [comment]
closing/re-opening PR. Build failed on exceptions twice within a 30 minute period.

**Comment by yogkumgit** [comment]
@Kateyanne

**Pull request merged**
