### PR TITLE
Update New-SafeLinksPolicy.md

### PR DESCRIPTION
**Pull request by briwilcox**
Added info on new cmdlet parameter

### CODE REVIEW

**Comment by briwilcox** [comment]
@Chrisda any update on this?

**Comment by chrisda** [comment]
@briwilcox, did you see the email I sent you? I still don't see this parameter in my PROD tenant. When is it expected to be "reasonably" WW? It doesn't need to be 100% but the 50% range is a good place to start.

**Comment by briwilcox** [comment]
> @briwilcox, did you see the email I sent you? I still don't see this parameter in my PROD tenant. When is it expected to be "reasonably" WW? It doesn't need to be 100% but the 50% range is a good place to start.

I am told it will take 72 hours to rollout and rollout will begin Monday Oct 4th so 50% would be Oct 5th.

**Comment by chrisda** [comment]
Cool. I'll merge so it publishes Tu 10/5 AM.

**Pull request merged**
