### PR TITLE
Update Sync-CsOnlineApplicationInstance.md

### PR DESCRIPTION
**Pull request by HankNguyen-MSFT**
Additional params to the sync cmdlet.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by dariomws — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
@HankNguyen-MSFT 
Hi, Hank,

Thank you for your submission.

We cannot merge the PR until after you sign the CLA. Please see above:

image

After you sign it, please @ mention me so that I can merge the PR.

Thanks!

**Comment by HankNguyen-MSFT** [comment]
@tiburd thanks. I have signed the CLA.

**Pull request merged**
