### PR TITLE
Details about New MeetingRecordingExpirationDays

### PR DESCRIPTION
**Pull request by YuriySamorodov**
It appears parameter MeetingRecordingExpirationDays has been replaced with It appears Set-CsTeamsMeetingPolicy has a new parameter NewMeetingRecordingExpirationDays

image

image

And it keeps the changes:
image

### CODE REVIEW

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Comment by get-itips** [comment]
Checking...

**Comment by dariomws** [comment]
@YuriySamorodov I can see that both parameters appear in the code in the latest version (2.6.0). My apologies but I cannot provide more information.

**Comment by get-itips** [comment]
the image shows an error when you try to run MeetingRecordingExpirationDays, it says the parameter is not there.

**Comment by get-itips** [comment]
@salarson Ok, thanks for clarifying.
@YuriySamorodov Can you add that note? thanks

**Comment by YuriySamorodov** [comment]
> @YuriySamorodov you can do it in the same PR. Just click the following button and edit the file: image

Thanks @dariomws. This is completed. Formatted the note in plain text to be readable in the terminal.

**Pull request merged**
