### PR TITLE
[Do not merge yet] Update policy package documentation

### PR DESCRIPTION
**Pull request by icchan8**
Group assignment feature:
- Status update: TAP -> GA

Custom package feature:
- Status update to show it is in TAP
- Update outdated links
- Update documentation to make it easier for readers to follow

### CODE REVIEW

**Review by tseward — APPROVED** [review]

**Comment by dariomws** [comment]
@yogkumgit, please don't forget to add @get-itips here.

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]
Hi @icchan8,

I cannot find the cmdlet Grant-CsGroupPolicyPackageAssignment in the GA or public preview versions.
Maybe the note "This cmdlet is currently in private preview." should be there too.

**Comment by icchan8** [comment]
Hi @dariomws,

Thanks for noticing that, just a little more context: Grant-CsGroupPolicyPackageAssignment will be released in GA in the next teams module release. This documentation update is partly in prep for that. I'll get this merged once we get closer to the release date.

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Pull request merged**
