### PR TITLE
Fixed -User; Added Param ChannelUserId & ChannelId

### PR DESCRIPTION
**Pull request by DEberhardt**
ChannelId, ChannelUserObjectId, OboResourceAccountIds

Text taken 1:1 from New-CsCallQueue
OboResourceAccountIds text taken from Admin Center

### CODE REVIEW

**Comment by get-itips** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7871

**Review by get-itips — CHANGES_REQUESTED** [review]
add the new parameters to the parameters section please

**Comment by dariomws** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/pull/7881

**Review by dariomws — CHANGES_REQUESTED** [review]
Thank you @DEberhardt!

Agree with @get-itips  and also some more small suggestions.

Could you kindly remove the OboResourceAccountIds parameter as it's being added in other PR:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/7881

**Comment by DEberhardt** [comment]
shall i close my PRs then?

**Comment by DEberhardt** [comment]
Updated (removed parameter OboResourceAccountIds).

**Review by dariomws — APPROVED** [review]
Thank you so much @DEberhardt.

Please don't forget to add the additional line break I'm suggesting.

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by tseward — APPROVED** [review]

**Review by JohanFreelancer9 — COMMENTED** [review]
Copy review - @DEberhardt, please commit the suggested change (additional linebreak). Many thanks.

**Comment by DEberhardt** [comment]
Done, thought I had already adopted the proposed line break. strange. Apologies. here it is now, all updated :)

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Pull request merged**
