### PR TITLE
Update Get-CsTenant.md

### PR DESCRIPTION
**Pull request by alexdale0**
Updating some of the docs from the Skype for Business cmdlets which have been modernized for Microsoft Teams. This specifically deals with Get-CsTenant.

### CODE REVIEW

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]
The DomainController parameter is still available in version 2.5.1. It might be a good idea to leave it.

**Comment by yogkumgit** [comment]
@tseward

**Comment by alexdale0** [comment]
> The DomainController parameter is still available in version 2.5.1. It might be a good idea to leave it.

Kept this in and just marked that it will be deprecated in near future.

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
