### PR TITLE
Update Set-SPOOrgNewsSite.md

### PR DESCRIPTION
**Pull request by dariomws306**
https://github.com/MicrosoftDocs/office-docs-powershell/issues/3168

### CODE REVIEW

**Comment by tseward** [comment]
FYI it looks like this commit has a misspelling of 'multiple'.

**Comment by kenwith** [comment]
@tseward - yes you are correct. I missed that too. @dariomws306 can you fix?

**Comment by dariomws306** [comment]
Hi @tseward and @kenwith , thank you, I didn't see it before, it was in the article.

**Comment by dariomws306** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/pull/3197

**Pull request merged**
