### PR TITLE
add possible PolicyType values

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness-pr/issues/13738

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by JohanFreelancer9** [comment]
> @JohanFreelancer9

@yogkumgit this is still a draft.

**Comment by get-itips** [comment]
@yogkumgit Waiting on internal information

**Comment by get-itips** [comment]
@mineliza-ms can you please review? Thanks

**Comment by shivtorov** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/issues/11189#issuecomment-1796935834

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tomkau Gentle reminder, kindly review. Thanks

**Comment by yogkumgit** [comment]
@tiburd Please help. Thanks

**Comment by michbrown-png** [comment]
@yogkumgit - are these changes still needed?

**Pull request merged**
