### PR TITLE
Create export-csonlineaudiofile.md

### PR DESCRIPTION
**Pull request by CLYVR**
New cmdlet documentation

### CODE REVIEW

**Comment by CLYVR** [comment]
@CarolynRowe Please review.  Updating *-CsOnlineAudioFile cmdlet documentation to add new Export-CsOnlineAudioFile cmdlet.  New cmdlet is due to go live Nov.8 and hoping to have new documentation available for then.  If there are any questions or issues please let me know.

**Comment by CarolynRowe** [comment]
Hello @CLYVR.  I have done a spot check of files and I am not seeing the disclaimer in some of the files.  Also, I would recommend adding the disclaimer to the top of the file--not hidden at the end of the description.  
Also, please note that I do not have write access to the PowerShell repo, which means I cannot help with merging to master.  Let me know if you have any questions.

**Comment by CLYVR** [comment]
@CarolynRowe - this PR (#8560) doesn't have the disclaimer - it's for the new Export cmdlet.  PR8561 should have the disclaimers at the top of the file.

Do you know who I need to @ mention for the PowerShell repo?

**Comment by CarolynRowe** [comment]
Hello @CLYVR.  You have the disclaimer at the end of the description.  I'm recommending moving it to the top of the page--so customers don't have to scroll and read the entire description before finding out that the cmdlet is deprecated.  If it's a long description, the disclaimer might be overlooked.

**Comment by CLYVR** [comment]
@tiburd Would you be able to merge these changes for the *-CsOnlineAudioFile cmdlets to master for me please?  We've added a new Export-CsOnlineAudioFile cmdlet that goes live today so I have added the page for the new cmdlet and updated the other cmdlets to show it as a related cmdlet.  If there are any questions please let me know.  Thanks!

**Comment by tiburd** [comment]
@CLYVR 
Hi Colin,
After our reviewers approve it, I can merge it.
Thanks!

**Comment by tiburd** [comment]
@get-itips @dariomws @tseward 
Hi!
Please review ASAP, and @ mention me after the last review.
Thank you!

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by CLYVR** [comment]
@tiburd Looks like the team has approved the changes.

**Pull request merged**
