### PR TITLE
Updating Get-CsOnlineUser cmdlet

### PR DESCRIPTION
**Pull request by praspatil05**
Updating Get-CsOnlineUser cmdlet to provide updated information for respective clouds

### CODE REVIEW

**Comment by praspatil05** [comment]
@JohanFreelancer9, could you help me in understanding, if this PR can be merged. Please do let me know if I am missing anything. Thanks!

**Comment by praspatil05** [comment]
Hello @tiburd could you please help and advise me to understand, if this PR can be merged. Please do let me know if I am missing anything. Thanks!

**Comment by chrisda** [comment]
@praspatil05, yes, it certainly can, but I don't know who's responsible for Skype/Teams. I have the power to merge PRs in the repo, but whomever is responsible for Skype/Teams and/or this article should really do the merging.

**Comment by praspatil05** [comment]
Thanks for your reply @chrisda. If possible, could you please advise me on whom should I reach out to for Skype/Teams. I was trying to take reference from a previous pull request - https://github.com/MicrosoftDocs/office-docs-powershell/pull/10889

**Comment by chrisda** [comment]
@praspatil05, I replied in email.

**Pull request merged**
