### PR TITLE
Update Connect-MicrosoftTeams.md

### PR DESCRIPTION
**Pull request by Rash-598**
Corrected the Syntax parameter set for AccessToken

### CODE REVIEW

**Comment by pbafna03** [comment]
@Rash-598 - thanks Rahul for initiating this change in the doc. 

2 comments:
(a) Have we removed this Param (-AccountId) totally from Connect-MicrosoftTeams in all scenarios? 

(b) If yes, in the bottom part of the page where we have description for "-AccountId" - I would suggest adding a line there - something on the lines of  - This parameter is removed from TPM version x.y and is not needed going forward.  Very similar to what we have for -AadAccessToken

**Comment by Rash-598** [comment]
It is not removed. It is seperated from accesstoken flow
Updating the account id description

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by dariomws — CHANGES_REQUESTED** [review]
@Rash-598, AccessTokens parameter set should be removed from AccessTokens parameter description.

**Comment by get-itips** [comment]
> @Rash-598, AccessTokens parameter set should be removed from AccessTokens parameter description.

Dario meant from the _AccountId parameter description_.

**Comment by yogkumgit** [comment]
@Rash-598 Please update. Thanks

**Comment by Rash-598** [comment]
Hi @dariomws @get-itips @yogkumgit 
The access token is removed from _AccountId_ description

**Comment by get-itips** [comment]
@Rash-598 Hello Rahul, we meant the parameter description:

image

**Comment by Rash-598** [comment]
Done. Please check

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
