### PR TITLE
Update New-UnifiedAuditLogRetentionPolicy.md

### PR DESCRIPTION
**Pull request by brucehuy**

### CODE REVIEW

**Comment by brucehuy** [comment]
@lindalu-MSFT please approve

**Comment by lindalu-MSFT** [comment]
@brucehuy Hi Bruce, sadly this is one of the few repos that I don't have admin privileges.

**Comment by chrisda** [comment]
I'm not an admin either, but I have Write access to the repo, so I can approve your PR.

Except that your corrected sentence now contradicts itself. It now says:

> A lower integer value indicates a higher priority, the value 1 is the lowest priority, and policies can't have the same priority value.

Should it say:

> A **higher** integer value indicates a higher priority, the value 1 is the lowest priority, and policies can't have the same priority value.

**Comment by brucehuy** [comment]
Good catch.  Updating and re-submitting.

**Comment by brucehuy** [comment]
I just sent a new PR.

**Pull request merged**
