### PR TITLE
Grant-CsHostedVoicemailPolicy.md not applicable to Teams

### PR DESCRIPTION
**Pull request by dariomws**
Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/8918.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by dariomws** [comment]
image

**Comment by yogkumgit** [comment]
@tseward @get-itips

**Comment by dariomws** [comment]
Thanks @get-itips. I understand it's available only for SfB onprem.

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
