### PR TITLE
Deprecation notice for application endpoint cmdlets

### PR DESCRIPTION
**Pull request by elvinyang-msft**

### CODE REVIEW

**Comment by elvinyang-msft** [comment]
@officedocspr folks could you please help to merge this PR please? Thanks!

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
