### PR TITLE
Update New-CsTeamsVoiceApplicationsPolicy.md

### PR DESCRIPTION
**Pull request by CLYVR**
Putting parameters in alpha order

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by yogkumgit** [comment]
@tiburd Gentle reminder. Thanks

**Pull request merged**
