### PR TITLE
Country/CountryAbbreviation changes to Get-CsOnlineUser

### PR DESCRIPTION
**Pull request by pbafna03**
Raising PR on Isaiah's behalf as he is OOF for changes wrt Country & CountryAbbreviation in Get-CsOnlineUser

### CODE REVIEW

**Comment by pbafna03** [comment]
Note - This PR to be merged only post 13th April'22.

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by dariomws — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
