### PR TITLE
Update TOC for Teams PowerShell documentation

### LINKED ISSUE #8117: The Overview and Introduction pages are nearly identical
There appear to be two pages that are only slightly different from each other.  Was this an accidental duplication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03f9b8-7a1f-81e7-e8c2-0286f0cd3ffb
* Version Independent ID: 931924d1-2be2-bc20-41a6-0b86fc65db07
* Content: [Microsoft Teams cmdlet reference](https://docs.microsoft.com/en-us/powershell/teams/intro?view=teams-ps)
* Content Source: [teams/docs-conceptual/intro.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/teams/docs-conceptual/intro.md)
* Service: **teams-powershell**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

### PR DESCRIPTION
**Pull request by DMoenks**
Fixes #8117

As stated in the issue description, the **Overview** and **Introduction** pages are mostly identical, differing only regarding the current status of **Skype for Business Online** and **Teams** PowerShell cmdlets. As all those cmdlets are now part of the Teams PowerShell module, the **Introduction** page is outdated and should safely be removable from a documentation perspective.

### CODE REVIEW

**Comment by DMoenks** [comment]
Based on the pull request checks, a redirect would be suggested due to a file being deleted. I can't access the relevant documentation though, as this seems to be accessible only to Microsoft staff.
If a redirect is something I could commit as part of the pull request, please let me know how to do this and I'll gladly make necessary changes.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Comment by get-itips** [comment]
> @dariomws @get-itips @tseward

@yogkumgit please see email thread with @traya1 we are waiting for approval about this change.

**Comment by tiburd** [comment]
Approved by Serdar via email.
Thanks!

**Comment by get-itips** [comment]
Thanks @tiburd

**Pull request merged**
