### PR TITLE
Update Get-CsOnlineVoiceUser.md - Minor changes

### PR DESCRIPTION
**Pull request by isrumnon**

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by dariomws — APPROVED** [review]
@isrumnon, could we add a description for this parameter? Thanks!

**Comment by yogkumgit** [comment]
@get-itips

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
