### PR TITLE
[Hold] Adding Custom Property names table Update Get-CalendarDiagnosticObjects.md

### PR DESCRIPTION
**Pull request by telaws**
Customers are unable to take logging output from Get-CalendarDiagnosticLog and convert valid output from Get-CalendarDiagnosticAnalysis, the latter is broken is EXO and results in a Watson OutOfRange error, open active bug linked.

Tenant Admins only workaround is to use Get-CalendarDiagnosticObjects, but by default they will only get 63 out of the 220+ available properties. 

Extra properties can be entered via the CustomPropertyNames parameter, however they are not publicly documented
Attached file has Values and Descriptions:
Excluding deprecated values for NetMeeting and those that returned InvalidSchemaProperty, requires review:
CustomProperyNameValuesAndDescriptions_ContentIdeaSubmission.csv
Shane Ferrell EEE from Calendaring Platform recommended Rob Whaley as a writer to get these updated in documentation.
See Attached email in files
RE VSO 1550318 - 193709351 - Customer Escalation Ask  Get-CalendarDiagnosticObjects - Discovering StoreProps for CustomPropertyNames.msg

Per Shane Ferrell we also need to add updates for these, or would this be a different request ? See attached email
Also need to update the Get-CalendarDiagnosticObjects documentation with regards to new parameters: 
-ShouldFetchAttendeeCollection, -EwsID, -ConfigurationName

### CODE REVIEW

**Comment by telaws** [comment]
@tweekerz and @scorrea4099 please review and let scorrea@microsoft.com or telaws@microsoft.com know if you have any questions.

**Comment by chrisda** [comment]
@telaws, you can't add a random section or a table in a cmdlet reference topic. It violates the schema.

**Comment by chrisda** [comment]
@telaws, I swear I already commented about this yesterday, but you pull request won't validate because you can't add random sections or any tables to a cmdlet reference topic. It violates the schema as defined [here](https://github.com/PowerShell/platyPS/blob/master/platyPS.schema.md). Even if formatted correctly and placed in the correct location, the sheer volume of information might not be appropriate for a cmdlet reference topic.

**Comment by scorrea4099** [comment]
@chrisda @telaws This came out of an internal thread to make the values for the CustomPropertyNames parameter public. Would this work better as a blog post ? What would be the best place for documenting a voluminous table for this cmdlet, and getting this information out there.

**Comment by tweekerz** [comment]
@chrisda @telaws @scorrea4099 Will follow up over email.

**Comment by chrisda** [comment]
Closing this PR. I'm working on a new conceptual topic in the Exchange conceptual area of the repo that contains that big table of information. Will reference this PR if/when that new topic goes live.

**Pull request closed without merging**
