### PR TITLE
Update Connect-MicrosoftTeams.md

### PR DESCRIPTION
**Pull request by alexdale0**
Add a warning that basic auth is needed to run legacy *-Cs cmdlets. Related to https://github.com/MicrosoftDocs/office-docs-powershell/issues/7518 and https://github.com/MicrosoftDocs/office-docs-powershell/issues/7464 and https://github.com/MicrosoftDocs/office-docs-powershell/issues/7824

### CODE REVIEW

**Comment by mark3grahams** [comment]
Hi alexdale0,

I do not think this is a basic auth issue. It works fine as with user creds. This error presents when using an app registration.

Can you get this working? If so, how?

**Comment by alexdale0** [comment]
Hi @mark3grahams -  that's what this warning added to the docs is also saying. You must use basic auth/user creds, as authentication with Application ID+Certificate is not supported currently.

**Comment by mark3grahams** [comment]
So, it is flat-out broken? That's what I thought. Is there an ETA as to when this will be fixed? Or is there some other method whereby a script can run without a user account?

**Comment by alexdale0** [comment]
> So, it is flat-out broken? That's what I thought. Is there an ETA as to when this will be fixed? Or is there some other method whereby a script can run without a user account?

Unfortunately I don't have an ETA at this time. Will be sure to get these docs updated further when that changes though.

**Review by get-itips — APPROVED** [review]

**Review by dariomws — COMMENTED** [review]
@alexdale0 Did you realize that the link you added is related to Exchange Online? Thanks!

**Comment by yogkumgit** [comment]
@tseward

**Comment by alexdale0** [comment]
Hi @dariomws - I did, as it has some good info related to the warning message. If that's not a good practice let me know and I can see if I can find a reference somewhere else though.

**Review by dariomws — COMMENTED** [review]
@alexdale0,

I cannot clearly see how it's related but I'm approving it because it could be a personal interpretation.

Thanks!

**Review by dariomws — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
