### PR TITLE
Add one more support language

### PR DESCRIPTION
**Pull request by Jicwang**
Add one more invite language

### CODE REVIEW

**Comment by Jicwang** [comment]
Hi @tiburd 
Could you help review the PR.  I don't have write permission, could you also help merge the PR. Thank you

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by Jicwang** [comment]
@dariomws 
Could you help review this PR. Thank you for the help. ;)

**Review by dariomws — APPROVED** [review]

**Comment by Jicwang** [comment]
Hi @tiburd 
Could you help merge the PR. Thank you. ;)

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks.

**Pull request merged**
