### PR TITLE
Update Grant-CsTeamsAppPermissionPolicy.md

### PR DESCRIPTION
**Pull request by unicornpancakes**
Note block added replacing the bold Note. These changes fit Microsoft's style guide.

https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines?view=powershell-7.3

### CODE REVIEW

**Review by JohanFreelancer9 — COMMENTED** [review]
Copy review - @unicornpancakes, alert formatting, such as NOTE blocks, does not render correctly in the Synopsis section of PowerShell cmdlets. Therefore, the first Note should stay as is. The second Note under the Description section, however, can be changed as per your suggestion.

**Comment by dariomws** [comment]
Hi @unicornpancakes, thank you for your contribution.

In cmdlet’s articles the [!NOTE] (also [!IMPORTANT] & [!CAUTION]) should not be used because it can’t be rendered later by the Get-Help cmdlet in the console window.

**Review by dariomws — COMMENTED** [review]
Hi @unicornpancakes, thank you for your contribution.

In cmdlet’s articles the [!NOTE] (also [!IMPORTANT] & [!CAUTION]) should not be used because it can’t be rendered later by the Get-Help cmdlet in the console window.

**Review by get-itips — COMMENTED** [review]
I'm ok once suggestions applied

**Comment by yogkumgit** [comment]
@unicornpancakes Gentle reminder. Thanks

**Comment by unicornpancakes** [comment]
Ack, thank you!

**Pull request closed without merging**
