### PR TITLE
Upload TeamsEnhancedEncryptionPolicy md

### PR DESCRIPTION
**Pull request by xinawang**
Upload TeamsEnhancedEncryptionPolicy md

### CODE REVIEW

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Comment by get-itips** [comment]
@xinawang  if you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html.

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=xinawang

**Comment by yogkumgit** [comment]
@tseward

**Comment by tiburd** [comment]
@ashgupt 
Hi, Ashish - this PR is merged now. The changes should appear on the live site shortly after the afternoon publish (approximately 3:30 PM, Seattle time).
Thanks!

**Comment by ashgupt** [comment]
@tiburd shows up as page not found, we are linking this page to public blog going out tomorrow, thereby tracking the publish status - thanks

Page - https://docs.microsoft.com/en-us/powershell/module/teams/set-csteamsenhancedencryptionpolicy

**Pull request merged**
