### PR TITLE
Added note that this cmdlet will not apply to Teams

### PR DESCRIPTION
**Pull request by FilippSe**
Added note that this cmdlet will not apply to Teams

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by get-itips — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward @dariomws

**Comment by yogkumgit** [comment]
@tseward @dariomws please review

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws Please review

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
