### PR TITLE
Update Set-CsTenantFederationConfiguration.md

### PR DESCRIPTION
**Pull request by ASolom1**
Adding information to the 'AllowedDomains parameter specifying that it can support up to 4,000 domains.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
@MikePlumleyMSFT Given that this https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/10270#pullrequestreview-1568750490 was closed, is this PR ok? Thank you

**Comment by MikePlumleyMSFT** [comment]
@ASolom1 is the limit only for allowed domains or is it a combo of allow/block?

**Comment by ASolom1** [comment]
@Mike ***@***.***>

@Ailin ***@***.***> - do you know the answer to Mike's question below?

**Comment by ASolom1** [comment]
It is a combo of allow & block lists.

From: Alex Solomon ***@***.***>
Sent: Tuesday, August 29, 2023 7:59 PM
To: MicrosoftDocs/office-docs-powershell ***@***.***>; MicrosoftDocs/office-docs-powershell ***@***.***>; Mike Plumley ***@***.***>; Ailin Menabil ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/office-docs-powershell] Update Set-CsTenantFederationConfiguration.md (PR #11205)

@Mike ***@***.***>

@Ailin ***@***.***> - do you know the answer to Mike's question below?

**Comment by get-itips** [comment]
@MikePlumleyMSFT are we still ok to document this? Thanks

**Comment by yogkumgit** [comment]
@MikePlumleyMSFT Kindly update.

**Pull request merged**
