### PR TITLE
Update Set-CsBusyOptions.md

### PR DESCRIPTION
**Pull request by dariomws306**
I have completed synopsis, description, examples, parameters description, inputs, outputs and related links.

### CODE REVIEW

**Comment by kenwith** [comment]
@dariomws306 - the schema is really picky. If you get any validation errors ping me and I can help troubleshoot. Even just a heading where it doesn't expect one will throw error. I have even had a space in the wrong place that broke the schema. Just ping me and I can help. It takes awhile to get the hang of what it exactly wants. Thanks for working on these!

**Comment by dariomws306** [comment]
Thanks Ken, is a pleasure to work with you. I have got the same error for Set-CsBusyOptions and Remove-CsBusyOptions.md, but nothing for Get-CsBusyOptions. I have got "Expect hyperlink, but got *" in the Outputs section. Maybe the space? Thanks

**Comment by kenwith** [comment]
Might be, do you want to reopen this PR and I can check too?

**Comment by kenwith** [comment]
Or submit another.. either way.   It is a common issue to get little errors with schema though so will just take time to get the hang of what it complains about.

**Comment by dariomws306** [comment]
Yes, I am checking all spaces. I will try to figure it out, if I cannot I will ask you for help 😊 Thanks!

 

De: Ken Withee <notifications@github.com> 
Enviado el: viernes, 25 de mayo de 2018 16:44
Para: MicrosoftDocs/office-docs-powershell <office-docs-powershell@noreply.github.com>
CC: Dario Woitasen <dario@woitasen.com.ar>; Mention <mention@noreply.github.com>
Asunto: Re: [MicrosoftDocs/office-docs-powershell] Update Set-CsBusyOptions.md (#1117)

 

Or submit another.. either way. It is a common issue to get little errors with schema though so will just take time to get the hang of what it complains about.

**Comment by kenwith** [comment]
Cool, here is the schema by the way: https://github.com/PowerShell/platyPS/blob/master/platyPS.schema.md

**Comment by dariomws306** [comment]
Yes, I saw it reading the overview/quick start. Thanks!

**Pull request closed without merging**
