### PR TITLE
Updates for making .md files compatible for PlatyPS .xml conversion

### PR DESCRIPTION
**Pull request by shriya999**
The docs files will be converted into the Get-Help of the PowerShell cmdlets using PlatyPS  (https://github.com/PowerShell/platyPS). Some files are not compatible for the New-MarkdownHelp cmdlet and so the xml files are not getting generated correctly:

image

This PR aims to fix that issue.

### CODE REVIEW

**Comment by shriya999** [comment]
@yogkumgit @get-itips @dariomws please review this PR

**Review by dariomws — COMMENTED** [review]
Hi @shriya999,

This is how it looks in GitHub:
image

Is it expected that docs show one cmdlet per line? I'm not sure. Thanks!

**Comment by shriya999** [comment]
Hi @dariomws , updated the PR to fix the spacing. Please take a look.

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by shriya999** [comment]
@tseward @tiburd please review this PR

**Comment by tiburd** [comment]
@tseward - please @ mention me after you finish your review. Thank you!

**Review by tseward — APPROVED** [review]

**Comment by tseward** [comment]
@tiburd done

**Comment by tiburd** [comment]
@shriya999 - I'll merge this PR now, but please fix the suggestions listed above regarding **IConfigApiBasedCmdletsIdentity** in a new PR. Thanks!

**Pull request merged**
