### PR TITLE
Remove note

### PR DESCRIPTION
**Pull request by abnan**
With the v5.5.0 release the change is available without the preview version, so removing the disclaimer

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by shivtorov** [comment]
pls consider adding description for `-CustomPromptsEnabled` / `-CustomPromptsPackageId` parameters

**Comment by abnan** [comment]
> pls consider adding description for `-CustomPromptsEnabled` / `-CustomPromptsPackageId` parameters

@shivtorov Can you elaborate on what you mean by `-CustomPromptsEnabled` / `-CustomPromptsPackageId` parameters? Not seeing any references on the pages and a simple web search didn't yield anything interesting

**Comment by shivtorov** [comment]
> @shivtorov Can you elaborate on what you mean by `-CustomPromptsEnabled` / `-CustomPromptsPackageId` parameters? Not seeing any references on the pages and a simple web search didn't yield anything interesting

Well, that was exactly my point 😉
Mentioned parameters exist in the cmdlets, but they are not documented in these help articles.
So, we are wondering what their meaning is.

Since this PR is marked as `Microsoft Submitter`, I assumed you might be able to get info the cmdlet owner about these params and add their description into your PR. If that's not the case, then just ignore my comment above.

image

**Comment by abnan** [comment]
I see what you mean @shivtorov Thanks for pointing it out. I will indeed get in touch with the cmdlet owner and ask them to update documentation for the new parameters you found. But it will likely be done in a separate PR.

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
