### PR TITLE
Updated Get/Remove and Add-SPOGeoAdministrator

### PR DESCRIPTION
**Pull request by j0rt3g4**
Get-SPOGeoAdministrator
Remove-SPOGeoAdministrator
Add-SPOGeoAdministrator

### CODE REVIEW

**Comment by kenwith** [comment]
@j0rt3g4 - please remove the visual studio files.. Only the cmdlet references should be checked in.

**Comment by kenwith** [comment]
You can make sure they are in your  .gitignore  file so they don't get checked in.

**Comment by j0rt3g4** [comment]
I will do it . No problem

**Comment by kenwith** [comment]
@j0rt3g4  - it looks like the PR is still trying to add some files that aren't cmdlet reference files. Can you check above?

**Comment by j0rt3g4** [comment]
Will do

**Pull request closed without merging**
