### PR TITLE
Added notes

### PR DESCRIPTION
**Pull request by mukeshHCW**
These notes help users to know specific cases when to use which parameter

Proposed by Ian Liu

### CODE REVIEW

**Comment by mukeshHCW** [comment]
@kenwith I have been trying to add some notes here.. but it is giving me error.. how do i resolve this..

**Comment by kenwith** [comment]
@mukeshHCW - it is the schema checker. It is something I have spent way to much time trying to figure out the errors too over the years. :)  The schema is so strict because the same markdown is converted to XML and checked into code so that Get-Help cmdlet works from the command line. The tool used to do that is an open source one called PlaytPS ( https://github.com/PowerShell/platyPS/blob/master/platyPS.schema.md ). Here is the schema it uses: https://github.com/PowerShell/platyPS/blob/master/platyPS.schema.md    I took a look and I think it has to do with the four pound signs.. I think it doesn't like those as headings because they don't match the schema.

**Comment by mukeshHCW** [comment]
So if i remove those four pounds.. will it work?
________________________________

**Comment by kenwith** [comment]
It is worth a try. The schema validation error can be a pain to track down but the error in the build report can sometimes be helpful. 

"Failed to parse this MAML markdown file due to :84:(1054) '#### Note: For Office 365 or Exchange online tenan...' Expect Heading level 3, please use PlatyPS to do content validation"

**Pull request merged**
