### PR TITLE
Adding missing params

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/7515

@hirenshah1 Hiren, can you please provide the missing descriptions? I appreciate

### CODE REVIEW

**Review by tseward — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by get-itips** [comment]
@hirenshah1 Hiren, can you kindly help me getting the missing descriptions?
@dariomws AGC seems related to Automatic Gain Control, what do you think?

**Comment by dariomws** [comment]
@get-itips Probably. It is not easy, but we could test it.

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Comment by v-dihans** [comment]
Hi @get-itips 

**Following are blocking issues that need to be resolved before we can merge:**

skype/skype-ps/skype/Set-CsMediaConfiguration.md
- Lines 427, 442, 457: Placeholder content displays on staging. Can the placeholders and headings be removed if there is no information available for them at this time?


***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master)

**Blocking**
- The content preview must be clean on staging. It cannot contain any obvious formatting issues.

***

Thanks

**Comment by get-itips** [comment]
> Hi @get-itips
> 
> **Following are blocking issues that need to be resolved before we can merge:**
> 
> skype/skype-ps/skype/Set-CsMediaConfiguration.md
> 
> * Lines 427, 442, 457: Placeholder content displays on staging. Can the placeholders and headings be removed if there is no information available for them at this time?
> 
> **Reference**
> 
> [Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master)
> 
> **Blocking**
> 
> * The content preview must be clean on staging. It cannot contain any obvious formatting issues.
> 
> Thanks

Hello @v-dihans Certainly, that is why I am asking for @hirenshah1 help in getting the missing information :). Will transform this PR into a draft to avoid confusion. Thank you

**Comment by v-dihans** [comment]
@get-itips  

I see what happened. When the `sign off` label is applied, it automatically enters our queue for review and merge.

Thanks!

**Comment by get-itips** [comment]
> @get-itips
> 
> I see what happened. When the `sign off` label is applied, it automatically enters our queue for review and merge.
> 
> Thanks!

Oh! that's new :) Thanks to you!

**Comment by get-itips** [comment]
@hirenshah1 Hiren, can  you help here? Thank you

**Comment by hirenshah1** [comment]
sorry, I am no longer part of Skype product team and don't recall this information. Please contact Ravi Kant Rao - alias RAVRAO for more details.

**Review by tseward — APPROVED** [review]

**Comment by garycentric** [comment]
I removed the hyphens from the "Example" headings due to their appearance on docs.microsoft.com. If the browser window isn't wide enough, they can be laid out like this:

image

**Pull request merged**
