### PR TITLE
PermanentlyClearPreviousMailboxInfo

### PR DESCRIPTION
**Pull request by mprentice22153**
I believe the published info is incorrect.  The parameter is only valid for Exchange Online, per the associated blog post.

### CODE REVIEW

**Comment by chrisda** [comment]
@mprentice22153, there have been a couple of issues about this (#7028, #7078). What I think is the definitive answer is here:

<https://github.com/MicrosoftDocs/office-docs-powershell/issues/7028#issuecomment-799715448>:

> Spoke with person assigned to my case today, and someone is working on updating the documentation. The switch is not supported in Exchange Online.

No question that the parameter is _available_. Whether or not the parameter is _functional_ is the question. If you have other information, please advise.

**Comment by mprentice22153** [comment]
The parameter and functionality is absolutely available within Office 365 Exchange Online.  Just ran it yesterday, hence my submission, on 80 mailboxes that were incorrectly created in EO.  Ran it a year ago within the same customer environment when we first setup the hybrid Exchange, and have run it in other customer EO environments.  I've never run it in an Exchange on-prem environment so I'm not aware that it actually works there and thus my confusion.

**Comment by mprentice22153** [comment]
All of this was done against a M365 tenant. Actual domain removed but user account names are actual.

Get-user -Identity AKruse@domain.com | select *recip*

PreviousRecipientTypeDetails RecipientType RecipientTypeDetails
---------------------------- ------------- --------------------
UserMailbox                  MailUser      MailUser

Get-user -Identity jgorlicki@domain.com | select *recip*

PreviousRecipientTypeDetails RecipientType RecipientTypeDetails
---------------------------- ------------- --------------------
None                         MailUser      MailUser

set-user -Identity AKruse@domain.com -PermanentlyClearPreviousMailboxInfo
Get-user -Identity AKruse@domain.com | select *recip*

PreviousRecipientTypeDetails RecipientType RecipientTypeDetails
---------------------------- ------------- --------------------
None                         MailUser      MailUser

**Comment by mprentice22153** [comment]
This article is actually referenced in the set-user details for the PermanentlyClearPreviousMailboxInfo parameter and it clearly states the functionality is available to EO.
https://techcommunity.microsoft.com/t5/exchange-team-blog/permanently-clear-previous-mailbox-info/ba-p/607619

**Comment by chrisda** [comment]
@mprentice22153, you had me at your first response, Updated to ExO only as you described (with editorial license and consistency with other parameters in the same fate).

**Pull request merged**
