### PR TITLE
Update New-CsCallQueue.md

### PR DESCRIPTION
**Pull request by matipiri**
Updating default values of ConferenceMode & PresenceBasedRouting to true. Since this is being implemented in voice apps task: https://skype.visualstudio.com/DefaultCollection/SBS/_workitems/edit/2625437

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Review by dariomws — COMMENTED** [review]
Hi @matipiri,

When this change will be released?

Default values are still false in the latest GA version of the TPM:
image

**Comment by dariomws** [comment]
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=matipiri

**Review by get-itips — COMMENTED** [review]
Also asking when these changes will be implemented, (we do not have access to the url provided) Thanks

**Comment by matipiri** [comment]
@dariomws @get-itips 
Changes on the backend will go live by next Thursday (25th Aug) and the cmdlet changes will go to production by end of this month (31st August)

Following is the related PR: 
Backend PR: https://dev.azure.com/skype/SBS/_git/sync_pstn_avs-oaa-admin/pullrequest/670288
PowerShell cmdlet PR: https://skype.visualstudio.com/SBS/_git/infrastructure_web_interfaces-powershell/pullrequest/670304

**Review by dariomws — APPROVED** [review]
Thanks @matipiri!

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
