### PR TITLE
Update Get-PnPApp.md

### PR DESCRIPTION
**Pull request by airdalle**

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @airdalle, I can merge this in, since actually, it's matching what @erwinvanhunen also just submitted the docs. In general, though PnP PowerShell is slightly special around the documentation side since it's automatically generated from the code. In this case, the right file to edit the documentation would be actually following (also to right row) - https://github.com/SharePoint/PnP-PowerShell/blob/master/Commands/Apps/GetApp.cs#L15. Thx still on the contribution, since these are really welcome to ensure that docs are up to date.

**Comment by airdalle** [comment]
Thank you @VesaJuvonen for the hint about what should be edited in order to do it right :-)

**Comment by airdalle** [comment]
Should I delete the branch ?

**Comment by VesaJuvonen** [comment]
Yes - You can delete the branch if you like. Your changes have been merged.

**Pull request merged**
