### PR TITLE
Update Get-SPOSiteGroup.md

### PR DESCRIPTION
**Pull request by dariomws306**
Fixed link reference.

### CODE REVIEW

**Comment by kenwith** [comment]
@dariomws306 - please remove the   /en-us/   from the URL.. with that removed the page will load in whatever language the persons browser is using that is viewing the page. Let me know any questions. Thanks!

**Comment by kenwith** [comment]
Went ahead and removed and committed to your branch so as soon as checks finish I will get this merged. :)

**Comment by dariomws306** [comment]
@kenwith , thank you!

**Comment by yogkumgit** [comment]
@VesaJuvonen please review and merge this Pull Request or provide feedback if it is not approved.

**Pull request merged**
