### PR TITLE
Adding installation instructions

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/7363

### CODE REVIEW

**Review by dariomws — CHANGES_REQUESTED** [review]
Install command was there:
image

But I think the format is not nice. Maybe you can leave your new version and remove the old one.

**Comment by get-itips** [comment]
@dariomws Good catch, wasn't expecting that, maybe because it is not enclosed in a code tag, will propose an improvement then

**Review by dariomws — APPROVED** [review]
Thank you!

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne

**Pull request merged**
