### PR TITLE
Update connect-sharepoint-online.md

### PR DESCRIPTION
**Pull request by salarson**
Add update cmdlet

### CODE REVIEW

**Review by get-itips — CHANGES_REQUESTED** [review]
Hello @salarson 
Thanks for the contribution.
The `update-module` installs a new version but keeps the older one too

image

Should we add information to uninstall (`Uninstall-Module`) the current one first?

**Review by dariomws — COMMENTED** [review]
@salarson thanks for this PR.

Agree with @get-itips.

And if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=salarson

**Comment by get-itips** [comment]
@salarson Sam, can you review our suggestions? Thanks

**Comment by yogkumgit** [comment]
@salarson Please implement the suggestions. PR is pending. Thanks

**Review by tseward — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by get-itips** [comment]
@salarson have you seen my suggestion? Thanks

**Pull request merged**
