### PR TITLE
Update Set-CsTeamsMeetingPolicy.md

### PR DESCRIPTION
**Pull request by emmaryan123**
Setting correct Who can register policy info and type is Boolean

### CODE REVIEW

**Review by dariomws — APPROVED** [review]
Thank you @emmaryan123!

The same update should be applied to New-CsTeamsMeetingPolicy.

**Review by get-itips — COMMENTED** [review]
The type seems not to be boolean, a boolean only accepts true or false
if the acceptable values are Everyone and EveryoneInCompany the type is String.
image

**Comment by yogkumgit** [comment]
@emmaryan123 Please update with feedback. Thanks

**Review by emmaryan123 — COMMENTED** [review]
Updating based on reviews

**Comment by emmaryan123** [comment]
@yogkumgit updated- thanks

**Comment by yogkumgit** [comment]
@get-itips  and  @tseward

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Pull request merged**
