### PR TITLE
Missing Type=SharedVoicemail in the Syntax section

### LINKED ISSUE #5216: Missing Type = SharedVoicemail
In the 1st paragraph "SharedVoicemail" is not listed as a valid value for -Type parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b10b3afe-6425-f0b7-3eb0-a17c6a9d6fef
* Version Independent ID: 9dec1f94-908b-0992-c986-084449965df0
* Content: [New-CsAutoAttendantCallableEntity (skype)](https://docs.microsoft.com/en-us/powershell/module/skype/new-csautoattendantcallableentity?view=skype-ps)
* Content Source: [skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/skype/skype-ps/skype/New-CsAutoAttendantCallableEntity.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @tomkau
* Microsoft Alias: **tomkau**

### PR DESCRIPTION
**Pull request by shivtorov**
fixes #5216

### CODE REVIEW

**Comment by get-itips** [comment]
agree with @dariomws

**Comment by tseward** [comment]
`SharedVoicemail` needs to be defined for the `-Type` parameter in the parameter description. It looks like @dariomws covers that in his PR.

**Comment by kenwith** [comment]
@dariomws - I will go ahead and merge this and would you please update the doc directly with your updates? Thank you.

**Comment by dariomws** [comment]
> @dariomws - I will go ahead and merge this and would you please update the doc directly with your updates? Thank you.

@kenwith sure I will do.

**Pull request merged**
