### PR TITLE
Update Set-PnPTenantSite.md

### PR DESCRIPTION
**Pull request by YuriySamorodov**
Added description for some parameters

### CODE REVIEW

**Comment by yogkumgit** [comment]
@get-itips Please guide here. Thanks

**Comment by get-itips** [comment]
Hello @YuriySamorodov 
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to review your PR.

The documentation for PnP cmdlets is then synced from that repo into this one.

Thank you!

**Comment by yogkumgit** [comment]
@get-itips

**Comment by get-itips** [comment]
> @get-itips

This PR can be closed.

**Pull request closed without merging**
