### PR TITLE
Adding documentation for Get-CsTeamsEducationConfiguration and Set-CsTeamsEducationConfiguration cmdlets

### PR DESCRIPTION
**Pull request by prrathna**
The Get-CsTeamsEducationConfiguration and Set-CsTeamsEducationConfiguration cmdlets will be available in the 4.9.0 GA release of TPM. Soon after that, we will make the functionality of the cmdlets available to all tenants by updating the Config API ECS rollout.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by prrathna** [comment]
@yogkumgit do you know why this PR is blocked with this error and what I can do to resolve it? 
image

**Comment by tiburd** [comment]
@prrathna 
Hi,
I asked an admin about the error. They are looking into the issue.
Please @ mention me when the PR is ready to be merged. 
Thank you!

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by prrathna** [comment]
@tiburd @yogkumgit we'd actually like to wait to merge this PR until the Teams Powershell Module release for version 4.9.0 is released. The ETA is Oct 31

**Comment by tiburd** [comment]
I'm changing this to Draft and adding the date to the title to help make sure that it doesn't accidentally get merged early.

Please @ mention me when it's ready to merge.

Thank you!

**Review by tseward — APPROVED** [review]

**Pull request merged**
