### PR TITLE
Added note that this cmdlet will not apply to Teams

### PR DESCRIPTION
**Pull request by FilippSe**
Added note that this cmdlet will not apply to Teams

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by get-itips — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @tseward

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward please review

**Review by tseward — APPROVED** [review]

**Comment by tiburd** [comment]
close > reopen

**Pull request merged**
