### PR TITLE
Add document for Get/Set-CsOnlineVoicemailUserSettings cmdlets

### PR DESCRIPTION
**Pull request by CHILIU-MSFT**

### CODE REVIEW

**Comment by kenwith** [comment]
@tomkau @islubin  - OK to merge?

**Comment by tomkau** [comment]
@CHILIU-MSFT , how are these voicemail settings related to the hosted voicemail policy?

https://docs.microsoft.com/en-us/powershell/module/skype/new-cshostedvoicemailpolicy?view=skype-ps

Do tenant admins need to work with policy and settings?

**Comment by CHILIU-MSFT** [comment]
Hi @tomkau ,
HostedVoicemailPolicy is for tenants using Exchange UM. And we have another cmdlets set for tenants using Azure Voicemail:  Set-CsOnlineVoicemailPolicy  https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoicemailpolicy?view=skype-ps    Grant-CsOnlineVoicemailPolicy  https://docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoicemailpolicy?view=skype-ps

Policy and user settings are both used to control Azure Voicemail features. But they are in different level and they control different features.
In general, policy is a "tenant level" config. Policy can only be changed by tenant admin. Tenant admin could Set policy for the whole tenant or Grant a specific policy instance to a specific user. "Voicemail Transcription" and "Voicemail Transcription Profanity Masking" features are controled by policy.
But user settings is a "user level" config. Beside tenant admin could change user settings using Get/Set-CsOnlineVoicemailUserSettings cmdlets, there's a "User Settings Portal" and user can modify his own user settings throw this "USP". "Voicemail Enabled", "Out-of-office Greeting" and "Call Answer Rules" features are controled by user settings.

**Comment by CHILIU-MSFT** [comment]
@kenwith  @tomkau  Hi, does it make sense?

**Comment by tomkau** [comment]
Yes, that makes sense.  Thanks for clarifying!

**Pull request merged**
