### PR TITLE
Update Move-CsUser.md

### PR DESCRIPTION
**Pull request by Ravindra-Microsoft**
By default, SFB 2015 uses OAuth for Move user and there is no flag UseOAuth in SFB 2015 CU12 any more(Its explicitly removed from CU12)

### CODE REVIEW

**Comment by Ravindra-Microsoft** [comment]
@MicrosoftDocs/marveldocs-pubops PR is ready for review. Please review and publish.

**Comment by v-dihans** [comment]
@Ravindra-Microsoft  

Please add the "sign-off" label so the PR enters the queue and we can review it.

Thanks!

**Comment by Ravindra-Microsoft** [comment]
Hi Diana,

I have submitted PR in past and I didn't add "sign-off" label. Actually, I wasn't able to add label, and asked for help and I was advised to leave a comment.

Please refer the chat I had on this in past and advise.

***@***.***

Thanks.

Regards,
Ravindra Singh Bisht
Mobile: +91-9711729996

**Comment by Ravindra-Microsoft** [comment]
Hi Diana,

I have submitted PR in past and I didn't add "sign-off" label. Actually, I wasn't able to add label, and asked for help and I was advised to leave a comment.

Please refer the chat I had on this in past and advise.

image

**Comment by tiburd** [comment]
@get-itips @dariomws @tseward - whichever of you review this PR last, please @ mention me so that I can merge the PR.

Thank you!

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by Ravindra-Microsoft** [comment]
@MicrosoftDocs/marveldocs-pubops I don't see my changes in the live page yet . Can you help?
 https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps

**Comment by Ravindra-Microsoft** [comment]
Hi,

I don't see my changes in the live page yet . Can you help?

https://docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps

Thanks.

Regards,
Ravindra Singh Bisht
Mobile: +91-9711729996

**Pull request merged**
