### PR TITLE
Improve `EnabledWithoutIVR` details

### PR DESCRIPTION
**Pull request by dinabogdan**
Add additional details about what `EnabledWithoutIVR` value of `SpamFilteringEnabledType` variable actually means.

### CODE REVIEW

**Review by tseward — APPROVED** [review]

**Comment by dinabogdan** [comment]
Hi @get-itips! Since @JohanFreelancer9 and @tseward approved the PR, may you please merge it? Thanks!

**Review by get-itips — APPROVED** [review]

**Comment by dinabogdan** [comment]
Hi folks! Can I have this PR merged into master, please? Thanks!

**Comment by dariomws** [comment]
Hi @tiburd, could you kindly help here? Thanks!

@dinabogdan could you kindly verify the mapping between GitHub and Microsoft aliases? The blue "Microsoft submitter" label still doesn't appear here. Thanks!

**Comment by tiburd** [comment]
It looks like it is connected but not showing in this PR:
image

**Pull request merged**
