### PR TITLE
Added Set-SPOSiteScript

### PR DESCRIPTION
**Pull request by Linda-Editor**
This doc was causing build issues, so we published all the other docs and now I'm trying to publish this one again.

### CODE REVIEW

**Comment by Linda-Editor** [comment]
@VesaJuvonen  @kenwith  I don't understand what this build error means. It wasn't appearing before, and I didn't make any more changes to files in exchange...; the files I want to publish are now showing as succeeded, but this exchange error is causing the build to fail. :-(

**Comment by kenwith** [comment]
@Linda-Editor - checking

**Comment by Linda-Editor** [comment]
@kenwith Any headway on this? It's the only thing holding up publishing...thanks for your help.

**Comment by kenwith** [comment]
@Linda-Editor - try to trigger a new build now

**Comment by kenwith** [comment]
@Linda-Editor - this error above is likely something with the schema. Make sure the content matches exactly the schema.. it can be found here: https://github.com/PowerShell/platyPS/blob/master/platyPS.schema.md

**Comment by Linda-Editor** [comment]
Closing this PR because it's not moving...

**Pull request closed without merging**
