### PR TITLE
Renamed cmdlets name and description

### PR DESCRIPTION
**Pull request by bishalgautam-ms**
Renamed cmdlets name and description

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Comment by get-itips** [comment]
Hello @bishalgautam-ms 
Are you a Microsoft employee?

Here is a site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=bishalgautam-ms

And if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

There are some build errors because of the file name change, can you review them?

**Comment by bishalgautam-ms** [comment]
> Hello @bishalgautam-ms Are you a Microsoft employee?
> 
> Here is a site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=bishalgautam-ms
> 
> And if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html
> 
> There are some build errors because of the file name change, can you review them?

Hi @get-itips , yes I am a Microsoft employee. I can see the mapping between my GitHub alias and Microsoft alias in the above link.
I just fixed the build errors. Please have a look again. Thank you!

**Review by get-itips — COMMENTED** [review]
I couldn't find these cmdlets in 3.0.0 or 3.0.1-preview, is this going live in the next GA or Public Preview of the module? Thanks

**Comment by bishalgautam-ms** [comment]
> I couldn't find these cmdlets in 3.0.0 or 3.0.1-preview, is this going live in the next GA or Public Preview of the module? Thanks

Yes, we are planning to release it in the next GA, we will try to release this public doc update and that release as close as possible.

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by get-itips** [comment]
@bishalgautam-ms Bishal, your last commit seem to impact the build, can you check please?

**Comment by bishalgautam-ms** [comment]
> @bishalgautam-ms Bishal, your last commit seem to impact the build, can you check please?

Seems like build warning errors are coming for the file which does not even exist in the project (**_exchange/exchange-ps/toc.yml_**). I have not made any changes in files under that folder. This looks quite strange to me.

**Comment by get-itips** [comment]
Maybe @tiburd or @traya1  can help with that

**Comment by traya1** [comment]
looking into the issue

**Pull request merged**
