### PR TITLE
Improves the documentation of RequireAcceptingAccountMatchInvitedAccount

### PR DESCRIPTION
**Pull request by koskila**
This pull request improves the documentation of "-RequireAcceptingAccountMatchInvitedAccount" switch for Set-SPOTenant cmdlet. Adds notes to clarify when to use it and how quickly it's applied.

### CODE REVIEW

**Comment by kenwith** [comment]
@koskila - thanks for taking the time to improve the content! Much appreciated!

@VesaJuvonen - ok to merge?

**Comment by VesaJuvonen** [comment]
thx @koskila, appreciated.

**Comment by VesaJuvonen** [comment]
It worked good, so no issues on formatting. Thx.

**Comment by koskila** [comment]
My pleasure! Happy to hear it worked out ok.

**Pull request merged**
