### PR TITLE
Update Update-CsTeamTemplate.md

### PR DESCRIPTION
**Pull request by charlieforce**
I have removed the category and icon sections as they are editable

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — COMMENTED** [review]
Copy review - @charlieforce, should lines 639 and 670 be deleted?  If you look at the rich diff (preview), they are bullet points with no content. Thanks.

**Comment by yogkumgit** [comment]
@charlieforce Gentle reminder.

**Comment by yogkumgit** [comment]
@get-itips @dariomws @tseward

**Review by get-itips — COMMENTED** [review]
@charlieforce 
The parameters are present in 4.5.1-preview version of the module, are they going to be removed soon? Can you explain a little bit more the proposed changes? Thanks

**Review by dariomws — COMMENTED** [review]
They are also available in the latest GA version (4.6.0).

**Comment by yogkumgit** [comment]
@charlieforce We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we proceed to close this PR.  
Please feel free to re-open this PR or reach out to Author internally as you are a MS member.  Thanks again, for taking out some time to open the PR. Appreciate and encourage you to do the same in future also.

**Pull request closed without merging**
