### PR TITLE
Update New-CsAutoAttendantCallableEntity.md

### PR DESCRIPTION
**Pull request by CLYVR**
Removing deprecated parameters (OrganizationalAutoAttendant | HuntGroup)

### CODE REVIEW

**Comment by CLYVR** [comment]
@get-itips @dariomws @tseward @tiburd Minor update to remove deprecated parameters - THANKS!

**Review by tseward — APPROVED** [review]

**Comment by tiburd** [comment]
@dariomws 
Hi! 
Please @ mention me if it's ready to merge after your review. 
Thanks!

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]
@CLYVR, I can see them in the code (v3.1.1). Maybe instead of removing them, we can add a note or sentence in the description to let the reader know that they are deprecated. Someone can raise an issue asking for them based on my experience.
If they will be removed in the near future from the code, forget this comment.

Thanks!

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
