### PR TITLE
Add EnabledWithoutIVR SpamFilteringEnabledType value

### PR DESCRIPTION
**Pull request by dinabogdan**
Add EnabledWithoutIVR SpamFilteringEnabledType value for Set-CsTeamsCallingPolicy cmdlet

### CODE REVIEW

**Review by get-itips — APPROVED** [review]

**Comment by get-itips** [comment]
Can you also make the addition for the `New-` version of the article? Thanks

**Comment by dinabogdan** [comment]
> Can you also make the addition for the `New-` version of the article? Thanks

Could you please, point me to that specific file? Thanks!

**Comment by get-itips** [comment]
> > Can you also make the addition for the `New-` version of the article? Thanks
> 
> Could you please, point me to that specific file? Thanks!

I am sorry, my mistake, the cmdlet's article is not present yet, that will be added later probably. I am ok with the addition.

**Review by tseward — APPROVED** [review]

**Comment by dinabogdan** [comment]
> > > Can you also make the addition for the `New-` version of the article? Thanks
> > 
> > 
> > Could you please, point me to that specific file? Thanks!
> 
> I am sorry, my mistake, the cmdlet's article is not present yet, that will be added later probably. I am ok with the addition.

Can I have this PR merged, as @tseward approved it, please?

**Comment by get-itips** [comment]
> Can I have this PR merged, as @tseward approved it, please?
@Kateyanne

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Pull request merged**
