### PR TITLE
Update Grant-CsTeamsVideoInteropServicePolicy.md

### PR DESCRIPTION
**Pull request by rongqi-msft**
Add `-Global` in command line, that's the why our team suggest to do for tenant level change

### CODE REVIEW

**Comment by rongqi-msft** [comment]
Hi @Kateyann
Our team wants to update this command suggestion, I saw you help merge a most recent PR into the master, could you help review the change and merge it?

**Review by tseward — APPROVED** [review]

**Review by get-itips — COMMENTED** [review]
I think the -Global parameter should be to the left of the | pipe?

**Comment by get-itips** [comment]
> I think the -Global parameter should be to the left of the | pipe?

nevermind, I see know is part of the example

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Pull request merged**
