### PR TITLE
Policheck Update - July 24 | Bulk Update

### PR DESCRIPTION
**Pull request by damabe**
Fixes the following Policheck issues:

https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/111073
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/111083
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/111085
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/111087
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/111089
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/111092
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/111100
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/111103
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/111107

### CODE REVIEW

**Comment by damabe** [comment]
#sign-off This is a bulk update.

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by get-itips — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by damabe** [comment]
#sign-off This is a bulk update.

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
