### PR TITLE
Update New-CsTeamTemplate.md

### PR DESCRIPTION
**Pull request by charlieforce**
I have removed category and icons sections

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by dariomws — COMMENTED** [review]
Hi @charlieforce,

Could you kindly provide more information about this PR? It seems that the parameters are available in TPM 4.6.0. It will be expected that readers ask for them if they appear in the code.

Thanks!

**Review by JohanFreelancer9 — COMMENTED** [review]
Copy review - @charlieforce, should lines 641 and 672 be deleted?  If you look at the rich diff (preview), they are bullet points with no content. Thanks.

**Comment by yogkumgit** [comment]
@charlieforce Gentle reminder.

**Comment by yogkumgit** [comment]
@charlieforce Please answer and update the PRs. In the event of no reply we may proceed to close these PRs. Thanks

**Comment by yogkumgit** [comment]
@charlieforce We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we proceed to close this PR.  
Please feel free to re-open this PR or reach out to Author internally as you are a MS member.  Thanks again, for taking out some time to open the PR. Appreciate and encourage you to do the same in future also.

**Pull request closed without merging**
