### PR TITLE
Update New-UnifiedAuditLogRetentionPolicy.md

### PR DESCRIPTION
**Pull request by brucehuy**
@LauraWi @lindalu-MSFT we need to urgently revert this back as the documentation as originally intended should be the correct behavior and we should treat this as a code bug.

### CODE REVIEW

**Comment by brucehuy** [comment]
@Chris Davis ***@***.***> – can we approve this ASAP?  We need to urgently revert this back as the documentation as originally intended should be the correct behavior and we should treat this as a code bug instead of a doc bug.

**Review by JohanFreelancer9 — COMMENTED** [review]
@brucehuy, this appears to be a duplicate of PR #9333.

**Comment by lindalu-MSFT** [comment]
I don’t have permissions in this repo, sorry I can’t help.

Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by chrisda** [comment]
@brucehuy, always be mindful that 99% of the time, a change to a parameter in a New- cmdlet is also required in the corresponding Set- cmdlet.

I took care of this in PR #9340

**Pull request merged**
