### PR TITLE
Update Import-CsOnlineAudioFile.md

### PR DESCRIPTION
**Pull request by DMoenks**
Adjusted example sub-headers to bring them in-line with other docs and improve display in low-resolution/high-zoom cases

### CODE REVIEW

**Comment by DMoenks** [comment]
If this pull request is confirmed and merged, I might prepare a bunch of similar changes to other docs, as the differences in example sub-headers can be found in multiple places

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
