### PR TITLE
Adding Notes

### PR DESCRIPTION
**Pull request by nsshommo**
Adding important notes regarding cmdlet.

### CODE REVIEW

**Comment by kenwith** [comment]
@nsshommo - fast work!  Small type on "Important".

**Comment by nsshommo** [comment]
Fixed the typo.

**Comment by arachmanGitHub** [comment]
Table seems to be broken. Can you please make sure the table is correctly formatted for markdown @nsshommo

**Comment by nsshommo** [comment]
@arachmanGitHub Checking the table format now.

**Pull request merged**
