### PR TITLE
Add ViewInFileExplorerEnabled

### PR DESCRIPTION
**Pull request by salarson**

### CODE REVIEW

**Review by ConstantinDanStanciu — APPROVED** [review]
Looks good. Thank you!

**Review by get-itips — APPROVED** [review]

**Review by dariomws — COMMENTED** [review]
@salarson, Will this parameter be available in a future version?

image

**Comment by yogkumgit** [comment]
@tseward

**Comment by salarson** [comment]
@dariomws Yes we are just rolling this out so it should start populating in tenants soon.

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
