### PR TITLE
Dial Plan Cmdlets: Removing external access dialing parameters.

### PR DESCRIPTION
**Pull request by mskartikb**
Dial Plan Cmdlets no longer use parameters for external access dialing, since external access prefixes are now handled implicitly by normalization rules.
Removing all documentation references to external access dialing and 2 parameters used for the same -
- externalAccessPrefix
- optimizeDeviceDialing

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
Adding @JensTrier to the reviewers list

**Comment by tiburd** [comment]
@JensTrier 
Hi,
Can you please review and @ mention me if/when you approve?
Thanks!

**Comment by JensTrier** [comment]
@mskartikb I think it would be good to mention in the Notes section of the individual pages that these parameters were deprecated because they are not used anymore by the service and in which TPM module it happened. Also mention that Get-CsTenantDialPlan still shows them in output.

**Comment by mskartikb** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by mskartikb** [comment]
updated Notes sections for all tenant dial plan cmdlets with information about the changes.

**Review by JensTrier — APPROVED** [review]
@tiburd I approve

**Review by get-itips — APPROVED** [review]

**Pull request merged**
