### PR TITLE
Update Set-CsAuthConfig.md with the required step to run bootstrapper.exe to nake the changes effective

### PR DESCRIPTION
**Pull request by cludiam**
maybe under the Notes section mention the required run of bootstrapper to take effect of the changed settings:

### CODE REVIEW

**Comment by kenwith** [comment]
@dariomws306  or @get-itips -- OK to merge? This one beyond my knowledge. :)

@cludiam - thanks for taking the time to make the docs better, greatly appreciated!

**Comment by dariomws306** [comment]
Hi Ken,

 

It’s not ok to merge, you don’t have to run Bootstrapper, you have to run Enable-CsComputer to apply this.

 

Source:

https://support.microsoft.com/en-us/help/4346673/new-cmdlets-to-manage-skype-for-business-server-2015-authentication

 

I will add a note with this, please remove this PR.

 

 

Regards,

 

Dario

**Comment by kenwith** [comment]
Ok, thank you, @cludiam , I am going to go ahead and close this one but if you disagree please re-open and we can discuss more.

**Comment by dariomws306** [comment]
Hi @cludiam , thank you.

I think you can run bootstrapper but it's better/simpler if you run Enable-CsComputer.

Source: https://support.microsoft.com/en-us/help/4346673/new-cmdlets-to-manage-skype-for-business-server-2015-authentication

I will add the same note to this article.

**Comment by dariomws306** [comment]
@kenwith , https://github.com/MicrosoftDocs/office-docs-powershell/issues/2340 it was merged 7 days ago, I think you should leave this note. Thanks.

**Comment by kenwith** [comment]
@dariomws306 - sorry, my brain is fried, should I re-open this PR and merge or is there a different note?

**Pull request closed without merging**
