### PR TITLE
Update Set-CsAutoAttendant.md

### PR DESCRIPTION
**Pull request by RuiPereiraTabares**
Looks like some versions of PowerShell (e.g. 5.1) will convert CallHandlingAssociations to array, while others (e.g. 7.0) will convert them to list. Runing:
$autoAttendant.CallHandlingAssociations.GetType().Name
5.1 => CallHandlingAssociation[] 
7.0 => ArrayList

the examples used will work only in 7.0 and not in 5.1

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by dariomws — COMMENTED** [review]
Hi @RuiPereiraTabares,

I cannot see the difference:
image

image

**Comment by dariomws** [comment]
New-CsAutoAttendantCallHandlingAssociation also creates a CallHandlingAssociation object:

image

image

image

**Comment by get-itips** [comment]
@RuiPereiraTabares 
Last time I asked, Teams PowerShell **is not** officially supported in Core/7, so I think this should not be added at the moment.

@pbafna03 for confirmation

**Review by get-itips — COMMENTED** [review]
@RuiPereiraTabares
Last time I asked, Teams PowerShell is not officially supported in Core/7, so I think this should not be added at the moment.

@pbafna03 for confirmation

**Comment by RuiPereiraTabares** [comment]
@get-itips  the thing is that our example 3 will not work on powershell 5, so we need to either edit the example or mention that example 3 will only work with powershell 7

**Comment by pbafna03** [comment]
Yeah instead of this, I think better would be to tweak the example which doesn't work for PS 5. Also looping in @CLYVR .

**Comment by CLYVR** [comment]
> Yeah instead of this, I think better would be to tweak the example which doesn't work for PS 5. Also looping in @CLYVR .

Agreed - if Powershell 7 is not officially supported yet then we shouldn't be showing a powershell 7 example and should change it so it works with powershell 5

**Comment by RuiPereiraTabares** [comment]
well them this is the example 3 edititon for removing an callhandelingassociation

$autoAttendant.CallHandlingAssociations = $autoAttendant.CallHandlingAssociations | Where-Object{$_.ScheduleId -ne "0117420f-e04b-4b31-b370-9080ed6c4692"}

**Comment by get-itips** [comment]
@CLYVR @pbafna03 Thanks, I think Example 3 was working until a recent version of Teams PS that made it stop working, 
@RuiPereiraTabares can you edit your PR to use PS5 version of the example?
Thanks

**Comment by RuiPereiraTabares** [comment]
@get-itips done

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
