### PR TITLE
Update Set-SPOSite.md

### PR DESCRIPTION
**Pull request by msbemba**
Added Restrictions for Groups site collection

### CODE REVIEW

**Comment by kenwith** [comment]
@msbemba - please review the PR as there is a copy edit I did. I am not sure on the technical on this one and only reviewed the copy. CC @yogkumgit

**Comment by msbemba** [comment]
Thank you @kenwith Looks good to me.

**Comment by kenwith** [comment]
@msbemba - I think you have to click the button to commit the changes to your PR. This is new one to me so still learning. I tried to click the "commit suggestion" and it said I do not have permissions.

**Comment by msbemba** [comment]
@kenwith  I Clicked on the Commit suggestion and it worked. Thank you.

**Comment by kenwith** [comment]
@yogkumgit - for SPO cmdlets the owner is @VesaJuvonen and he can sign off on this one. I think it looks good but just want to confirm with him before I merge it.

**Comment by kenwith** [comment]
@msbemba - something else I just noticed.. you put paramset5 in the description section.. it should be just below paramset4.

**Comment by msbemba** [comment]
@kenwith  I see that and actually want this under the examples as a Note and not under the original paramset4 as that may confuse the reader. I may be wrong, But let me know if you want me to move this under paramset4 or change the description?

**Comment by kenwith** [comment]
yes, under paramset4 so it is clear paramset5 is continuation of it.. I might be misunderstanding but if there is another paramset how come it would go in description instead of with the other paramsets?

**Comment by kenwith** [comment]
One more thing too, in cmdlet reference we can't have the [!NOTE] markdown.. Since this same content displays in PowerShell terminal help when someone types    Get-Help cmdlet_name   so make sure we don't have any Markdown specific to things like Notes.  You could change it to text based like    NOTE: add note here.

**Comment by msbemba** [comment]
@kenwith  @VesaJuvonen  Added paramset5 under paramset4 and added a note.

**Pull request merged**
