### PR TITLE
Update Set-CsTeamsCallHoldPolicy.md

### LINKED ISSUE #9545: Example Correction
Hi, the examples on this page are misspelled: Set-TeamsCallHoldPolicy
instead of: Set-CsTeamsCallHoldPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 518fc90c-e8c9-a9a4-1fda-96424ca3d379
* Version Independent ID: 4958f385-ec82-e3ff-cff0-c667b9ee0249
* Content: [Set-CsTeamsCallHoldPolicy (SkypeForBusiness)](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallholdpolicy?view=skype-ps)
* Content Source: [skype/skype-ps/skype/Set-CsTeamsCallHoldPolicy.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/skype/skype-ps/skype/Set-CsTeamsCallHoldPolicy.md)
* Service: **skypeforbusiness-powershell**
* GitHub Login: @joelhmarquez
* Microsoft Alias: **jomarque**

### PR DESCRIPTION
**Pull request by DMoenks**
Resolves #9545
Rewrote examples to match cmdlet and parameter names

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
