### PR TITLE
Removing duplicate article

### PR DESCRIPTION
**Pull request by get-itips**
@TristanChen-msft @tiburd

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/11134

### CODE REVIEW

**Comment by shivtorov** [comment]
Closes #11134

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Comment by yogkumgit** [comment]
@tseward Gentle reminder

**Pull request merged**
