### PR TITLE
Update New-SafeLinksPolicy.md

### PR DESCRIPTION
**Pull request by joscurtis**
Updating this doc to reflect upcoming changes to the cmdlet parameters.
Rename: IsEnabled to EnableSafelinksForEmail
Remove duplicate parameters for: DoNotTrackClicks and DoNotAllowClickThrough in SafelinksPolicy
TrackClicks and AllowClickThrough: will not be changed or updated

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by chrisda** [comment]
Same questions/observations as #9074

**Comment by joscurtis** [comment]
Changes have been checked in and are deploying. They will reach SDF environment by Monday 03/14 and 100% WW by Friday 03/18.

For future reference is there a way to request updates to documentation but have the publishing delayed till a future date?
________________________________

**Comment by chrisda** [comment]
I now see that most of your changes are live. The only thing I don't see yet is the removal of the IsEnabled parameter. I added it back with the following description:

> This parameter has been deprecated and is no longer used.
>
> Use the EnableSafeLinksForEmail parameter instead.

**Pull request merged**
