### PR TITLE
Update Get-Team.md

### PR DESCRIPTION
**Pull request by glasserre**
GroupID and MailNickname parameters don't exist.

### CODE REVIEW

**Comment by kenwith** [comment]
@glasserre thank you for making the docs better! Please click the sign button on the cla above so the checks can finish. Thanks. :)

**Comment by kenwith** [comment]
@glasserre - would you please click the CLA to sign it so this PR can get through all the checks?

**Comment by tseward** [comment]
Both parameters are available for Get-Team in the module I have.

**Comment by kenwith** [comment]
@glasserre - Please reopen this PR if I am missing something but it appears these parameters exist in the module.

**Pull request closed without merging**
