### PR TITLE
Update Set-LabelPolicy.md

### PR DESCRIPTION
**Pull request by neha-dahiya**
Added EnableAudit in Advanced Settings, this setting is now supported in built-in labeling.

Review Requested - @cabailey @MikePaer-MSFT

### CODE REVIEW

**Comment by cabailey** [comment]
Looks great - sign-off from me!

**Comment by neha-dahiya** [comment]
> Looks great - sign-off from me!

I don't have write permissions, so can you merge this PR? Or I need to contact someone specific?

**Comment by cabailey** [comment]
#sign-off ready to merge

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Pull request merged**
