### PR TITLE
Create Get-CsSdgBulkSignInRequestStatus.md

### PR DESCRIPTION
**Pull request by Chandranshu-Singh**

### CODE REVIEW

**Comment by michbrown-png** [comment]
Hi @Chandranshu-Singh, can you please provide some descriptions for these parameters?
image
image
Our customers will not be sure of what the parameters do. Thanks for putting this file in the correct filepath

**Comment by Chandranshu-Singh** [comment]
These are some optional parameters that were picked up by the tool used to generate the MD file. We don't need these parameters. Since they got added by the tool, I left them there. Please feel free to remove. I don't have a description for them, as I don't know what they do.

**Comment by michbrown-png** [comment]
@Chandranshu-Singh , why are these parameters optional? If they are not needed, can your team disable them in the Teams PowerShell Module? We can delete the parameters from the documentation once they are removed from the Teams PowerShell Module. Any parameter that is available to customers in the Teams PowerShell Module must have corresponding documentation. We can't leave any parameter descriptions blank due to the risk of customer escalations

**Comment by Chandranshu-Singh** [comment]
@michbrown-png I have updated the PR, removed the parameters from documentation, these parameters were not added by us, so we will follow up with the Teams Admin Gateway team on why these were added. These seem like some hidden / internal params, which we don't need for our functionality.

**Pull request merged**
