### PR TITLE
Update New-CsAutoAttendantCallableEntity.md

### PR DESCRIPTION
**Pull request by CLYVR**
Adding new parameter for suppressing "Please leave a message after the tone" system prompt

### CODE REVIEW

**Review by get-itips — CHANGES_REQUESTED** [review]
Can you please add the parameter to Syntax section?

**Review by tseward — APPROVED** [review]
Approved once the requested changes are made.

**Review by dariomws — APPROVED** [review]
I'm ok once it's also added to syntax section.

**Comment by CLYVR** [comment]
Currently, the syntax section only shows the required parameters - for example, the existing -EnableTranscription parameter isn't in the syntax section and that's why I didn't add this new one as it's not a required parameter.  Do you want me to add both?

**Comment by dariomws** [comment]
@CLYVR Actually, the syntax sections must have all the parameters. Optional parameters enclosed between brackets and the mandatory parameters without them.

**Comment by CLYVR** [comment]
@dariomws Thanks for the clarification - I've added both parameters.

**Comment by dariomws** [comment]
Thank you @CLYVR!

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by CLYVR** [comment]
@dariomws @tseward @get-itips Just checking to see what needs to happen to get this merged into the live docs - is there something more I need to do?  Thanks!

**Comment by get-itips** [comment]
@Kateyanne can help merge

**Comment by garycentric** [comment]
I've removed the hyphens from the headings, because of how they appear on docs.microsoft.com.

## Before

image

<br/><br/>

## After

image

**Pull request merged**
