### PR TITLE
Not all parameter values available in all builds

### PR DESCRIPTION
**Pull request by sujnai**
The ManagedCustomFolder value returns output for all managed custom folders. The RecoverableItems value returns output for the Recoverable Items folder and the Deletions, DiscoveryHolds, Purges, and Versions subfolders. Folderscope parameter values LegacyArchiveJournals and NonIpmRoot are only applicable for Exchange 2013 and in addition to this Archives is added in Exchange Server 2016 and later.

### CODE REVIEW

**Comment by chrisda** [comment]
@sujnai, I'm ready to approve your changes, but I can't until you sign the Contributor License Agreement (CLA).

**Comment by sujnai** [comment]
> @sujnai, I'm ready to approve your changes, but I can't until you sign the Contributor License Agreement (CLA).

I have signed CLA now.

**Comment by sujnai** [comment]
> @sujnai, I'm ready to approve your changes, but I can't until you sign the Contributor License Agreement (CLA).

Additionally where we have written Exchange 2013 only, we should be mentioning Exchange 2013 and above only. 

How do I make this correction or do I make another edit once this is published?

Thanks,
Sujith Nair

**Comment by chrisda** [comment]
@sujnai, I fixed it.

**Pull request merged**
