### PR TITLE
Get-SPOTenant properties not documented

### PR DESCRIPTION
**Pull request by petey121175**
When running Get-SPOTenant the following properties show up and are lacking documentation. 

SyncPrivacyProfileProperties 
EmailAttestationRequired
EmailAttestationReAuthDays
StorageQuota (confirmation on Unit)
SyncPrivacyProfileProperties

### CODE REVIEW

**Review by get-itips — COMMENTED** [review]
You will find the definition for those parameters in the documentation for [Set-SPOTenant](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant)
Also, this shouldn't be a PR but maybe an "issue". Either way, the documentation is there where I pointed 😊

**Review by dariomws — COMMENTED** [review]
Agree with @get-itips.

**Comment by yogkumgit** [comment]
@petey121175 if you agree with @get-itips Please close this PR. Thanks

**Comment by himani-chi** [comment]
Hello,

I am the engineer who requested the PR to be created. The documentation in 'Set-SPOTenant' is severely lagging for these properties. It just splits the name of the property in the name of documentation and doesn't provide any useful information. For example: -

-EmailAttestationRequired
Sets email attestation to required.

_(what is email attestation here? Which email are we referring to)?_

-SyncPrivacyProfileProperties
This parameter enables the synchronization of privacy profile properties.

_(What are privacy profile properties? Where do they exist? Are we referring to the 'Show To' column in SharePoint User Profiles)? What are we synchronizing them with)? Are you referring to Delve as the destination?_

-EmailAttestationReAuthDays
Sets the number of days for email attestation re-authentication. Value can be from 1 to 365 days.

_(what is email attestation here? Which email are we referring to? Who receives these emails?_

- **StorageQuota** 

_This property does not exist in Set-SPOTenant. What's the Unit?_

Some additional properties returned by Get-SPOTenant that do not exist in Set-SPOTenant are: -

**AllowOverrideForBlockUserInfoVisibility**
**Workflows2013State**

**Comment by petey121175** [comment]
@get-itips If I need to I will open an issue on this. I think @himani-chi calls out the concerns. What exactly are would customers use these cmdlets for?

**Comment by get-itips** [comment]
> @get-itips If I need to I will open an issue on this. I think @himani-chi calls out the concerns. What exactly would customers use these cmdlets for?

Hello @petey121175 and @himani-chi thanks for returning and clarifying, yes please, that is the procedure, we need an issue to be created against that article to review it:

While browsing the article for Set-SPOTenant

https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps

click on _Submit and view feedback for **This Page**._

Thank you!

**Comment by yogkumgit** [comment]
@tseward

**Comment by yogkumgit** [comment]
@tseward Gentle reminder

**Pull request closed without merging**
