### PR TITLE
Corrected wrong example description

### PR DESCRIPTION
**Pull request by PowershellScripts**
The example 1 is about retrieving site design tasks, not scheduling them. 

The old description belongs to **Add**-SPOSiteDesignTask and not **Get**- and was probably a forgotten copy-paste.

### CODE REVIEW

**Comment by tseward** [comment]
I think scheduled is the wrong word for this. We don't 'schedule' site design applications, we run them and then can use this cmdlet to monitor status.

**Comment by dariomws306** [comment]
> I think scheduled is the wrong word for this. We don't 'schedule' site design applications, we run them and then can use this cmdlet to monitor status.

I think this cmdlet is to get/return previously scheduled Site Design Task add/create with Add-SPOSiteDesignTask. The word scheduled is all around the article so I think it's ok.

From Add-SPOSiteDesignTask article:
"Similar to Invoke-SPOSiteDesign, this command is used to apply a published site design to a specified site collection target. It schedules the operation, allowing for the application of larger site scripts (Invoke-SPOSiteDesign is limited to 30 actions and subactions)."

**Comment by tseward** [comment]
It's not a huge deal, but we don't "schedule" these tasks. We invoke them, which means start ASAP, but we can't say "run at 10 PM tonight".

Also, I see the explanation text is above the example, typically it is after the example.

**Comment by get-itips** [comment]
@PowershellScripts Thanks for your contribution
Can you also change the title metadata of the md file? it says Add-SPOSiteDesignTask

I am agree that the word scheduled is not maybe 100% accurate however it was there all over the article...

I am agree that the description of the example should be after the example.

**Comment by PowershellScripts** [comment]
About the word **schedule** - I agree with  @tseward that this is the behaviour we are seeing (speaking from user perspective), but that's the description used in every article on the topic, including PnP ones.  
  
On the description being above the example - it seems that a few articles follow this pattern. Would you like me to fix that?

**Comment by kenwith** [comment]
@PowershellScripts - thank you for the work on this and the excellent collaboration. Sounds like this one is ready to go. Appreciate all the discussion to make the docs are the best they can be. I am going to use this as an example on why community driven, open source, content is the best option. :)

**Pull request merged**
