### PR TITLE
Add deprecation notice to CCE cmdlets

### PR DESCRIPTION
**Pull request by firatakandere**
These cmdlets will soon be removed from Teams PowerShell module.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips @dariomws @tseward

**Review by get-itips — APPROVED** [review]

**Comment by firatakandere** [comment]
Please merge this PR.

**Comment by yogkumgit** [comment]
@dariomws @tseward

**Review by tseward — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
