### PR TITLE
Added -AsJob description to Get-CsOnlineUser.md

### PR DESCRIPTION
**Pull request by dariomws**
https://github.com/MicrosoftDocs/office-docs-powershell/issues/5717

### CODE REVIEW

**Comment by chrisda** [comment]
@dariomws, just FYI, AsJob is a common Windows PowerShell parameter that's available in remote PowerShell connections (similar to ErrorAction, ErrorVariable, etc.). [platyPS was updated](https://github.com/PowerShell/platyPS/issues/339) to not include that parameter (notice that it's not present in any Exchange-related cmdlets). I would consider a global search/replace effort to remove AsJob wherever you find it.

**Comment by dariomws** [comment]
@chrisda I'm going do it starting now.

**Comment by dariomws** [comment]
@chrisda done, new PR:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/5760

Maybe we should add some information about -Asjob here:
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
with these articles:
[about_Jobs](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_jobs)
[about_Remote_Jobs](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_remote_jobs)

**Comment by chrisda** [comment]
@dariomws, I wouldn't mess with that Common Parameters boilerplate, unless you're prepared to add the modified text to all future new cmdlets.

**Comment by dariomws** [comment]
Ok, understood. This text is added automatically by PlatyPS I think. Thanks!

Anyway, as you know, I'm available to help you with everything you need.

**Comment by dariomws** [comment]
Hi Chris,

I missed this. Do you want that I do a global search/replace to remove
AsJob?


Thanks,

Dario

**Pull request closed without merging**
