### PR TITLE
Update Get-CsOnlineUser.md - Removing redundant information

### PR DESCRIPTION
**Pull request by isrumnon**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by dariomws — APPROVED** [review]
@isrumnon, will you keep this only in the description section?

I think we should move the content in "Outputs" to "Notes".

**Review by get-itips — APPROVED** [review]
> I think we should move the content in "Outputs" to "Notes".

agree

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by yogkumgit** [comment]
@isrumnon your comments.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by isrumnon** [comment]
@tiburd I'm all done, please merge this PR

**Comment by tiburd** [comment]
> @tiburd I'm all done, please merge this PR

@isrumnon - can you please fix the file conflict and then @ mention me to merge?
Thanks!

**Comment by isrumnon** [comment]
@tiburd done from my end. Please go ahead and merge

**Pull request merged**
