### PR TITLE
Adding Parameter for -AllowCartCaptionsScheduling

### PR DESCRIPTION
**Pull request by bwilsonms**
Adding paremeter for controlling CART captions in meetings.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by dariomws — COMMENTED** [review]
Could we add this parameter to the New- cmdlet?

There are more missing parameters in this article (e.g. AllowMeetingCoach). Could we add them?

Currently, this article has 2 parameters sets  (identity and instance) but I think the cmdlet only has one.

**Comment by bwilsonms** [comment]
Can work on adding the additional paramenter mentioned for AllowMeetingCoach in the future and update the New- but for right now I wanted to get this one done for customer awareness.

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
