### PR TITLE
Adding documentation for new SfB Voice Apps' cmdlets

### PR DESCRIPTION
**Pull request by amrElroumy**

### CODE REVIEW

**Comment by kenwith** [comment]
Looping @islubin and @tomkau on these new cmdlets so we are all in sync. Let me know when I should go ahead and merge these.

**Comment by amrElroumy** [comment]
@kenwith The following warning is caused by a placeholder link, for a cmdlet that would be added by another team.
image

Is it OK to merge with that warning? Or do you prefer that I remove that link, till the other cmdlet documentation is added?

**Comment by kenwith** [comment]
@amrElroumy - go ahead and remove the link or comment it out or put a (coming soon) as a placeholder.. otherwise a dead link will show up in reports.

**Comment by amrElroumy** [comment]
@kenwith - You can merge this PR now. 
Thanks in advance.

**Pull request merged**
