### PR TITLE
Adding missing params

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/7170

### CODE REVIEW

**Comment by get-itips** [comment]
I must say that I don't like the param set names "get" "get1" however they are outputted like that using platyps... should I rename them? @tseward @dariomws

**Review by dariomws — APPROVED** [review]
@get-itips agree. Maybe we should use "Status (Default)" and "Identity". What do you think?

Also, I think we can separate the cmdlets from the output like we started to do in other articles and add the period at the end of each sentence.

**Comment by get-itips** [comment]
> Also, I think we can separate the cmdlets from the output like we started to do in other articles and add the period at the end of each sentence.

Can you kindly provide an example of that separation? I don't quite remember, thank you.

**Comment by tseward** [comment]
@get-itips  https://docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/powershell-style-guide?view=powershell-7.1#executable-examples

**Comment by get-itips** [comment]
> @get-itips https://docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/powershell-style-guide?view=powershell-7.1#executable-examples

Thanks!

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks.

**Pull request merged**
