### PR TITLE
Added Parameter OboResourceAccountIds

### PR DESCRIPTION
**Pull request by DEberhardt**
Text taken from Admin Center

### CODE REVIEW

**Comment by get-itips** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/issues/7871

**Review by get-itips — CHANGES_REQUESTED** [review]
please also add the parameter to the parameters section

**Comment by dariomws** [comment]
https://github.com/MicrosoftDocs/office-docs-powershell/pull/7881

**Review by dariomws — COMMENTED** [review]
Thank you @DEberhardt!

This parameter is being added in other PR:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/7881

**Comment by DEberhardt** [comment]
Closing this one as it is handled in #7881

**Pull request closed without merging**
