### PR TITLE
Clarify whatif and confirm behavior

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/10962

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@isrumnon Please comment. Thanks

**Comment by isrumnon** [comment]
@pbafna03 Will be looking after this area going forward

**Comment by yogkumgit** [comment]
@isrumnon Please suggest the next step. Thanks

**Comment by yogkumgit** [comment]
@tseward and @isrumnon Please let me know how to proceed with this PR. Thanks

**Comment by pbafna03** [comment]
@ruchiagrawal9221 can best comment on this as this is a Policy Grant cmdlet.

**Comment by yogkumgit** [comment]
@ruchiagrawal9221 Please help.

**Comment by ruchiagrawal9221** [comment]
> 

@yogkumgit  Agree with @tseward .. feature team should track the bugs separately.

**Comment by yogkumgit** [comment]
@get-itips

**Comment by yogkumgit** [comment]
@tseward what is expected?

**Comment by get-itips** [comment]
Then, closing.

**Pull request closed without merging**
