### PR TITLE
Remove MeetingRecordingExpirationDays

### PR DESCRIPTION
**Pull request by salarson**
Cmdlet to be replaced by new cmdlet

### CODE REVIEW

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Comment by yogkumgit** [comment]
@salarson Gentle reminder

**Comment by yogkumgit** [comment]
@tiburd kindly take the next appropriate step. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]
No copy to review.

**Comment by tiburd** [comment]
I sent email to @salarson asking for a reply.

**Comment by salarson** [comment]
Folks - Not sure what else is needed from me here but all references can be removed.

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Comment by dariomws** [comment]
@yogkumgit @tiburd, this PR can be closed since the updates were applied with another PR.

**Pull request closed without merging**
