### PR TITLE
Patch 10

### PR DESCRIPTION
**Pull request by dariomws306**

### CODE REVIEW

**Comment by dariomws306** [comment]
@tomkau could you review please?

I am not sure about -AdditionalAudienceUrls and -AlternateAudienceUrl on Set-CsOAuthConfiguration.

Thanks!

**Comment by tomkau** [comment]
@dariomws306, you can use the following description for both audience params:

An OAuth token includes an audience ("aud") claim that identifies the intended recipient of the token, in this case your Skype for Business Server.  The audience is typically expressed as a URL, such as https://skypeforbusiness.contoso.com, and is validated by the Skype for Business authentication module.  In some cases, depending on your authentication providers and/or other applications used in your organization, it may be necessary to allow multiple audience values to be used and recognized as valid by your Skype for Business server.

The AlternateAudienceUrl and AdditionalAudienceUrls parameters allow you to specify one or more additional audience values that will be recognized as valid by your Skype for Business server.

**Comment by tomkau** [comment]
@dariomws306, from what I can tell, there should not be much need for ClientAdalAuthOverride anymore. Let's use the following in the docs.  I'm intentionally being vague about ASDF/MEX to discourage non-advanced admins from doing it.

Modern authentication using Azure ADAL (Active Directory Authentication Library) is enabled by default for Skype for Business Online.   For authentication based on ADFS/MEX (metadata exchange), ADAL can be disabled by setting ClientAdalAuthOverride to Disallowed.

**Comment by dariomws306** [comment]
@tomkau thanks!

And what about the type of parameter? It's Object now.

**Comment by tomkau** [comment]
The fully qualified object type is:
Microsoft.Rtc.Management.WritableConfig.Settings.SSAuth.Hosted.ClientAdalAuthOverride

**Comment by dariomws306** [comment]
@kenwith I think we are done here.

**Pull request merged**
