### PR TITLE
Update Set-CsMeetingConfiguration.md

### PR DESCRIPTION
**Pull request by msbemba**
made the change for the attributte -DesignateAsPresenter   Company by default and not to none.

### CODE REVIEW

**Comment by kenwith** [comment]
@tomkau and @islubin - does this change look correct? Seems weird to me that PlatyPS set to "None"...

**Comment by kenwith** [comment]
@yogkumgit - I am just trying to get approval from @tomkau or @islubin on this change to make sure it is something they are aware and agree.

**Comment by tomkau** [comment]
The change is correct--matches the code

**Comment by kenwith** [comment]
Thanks @tomkau ! Will merge.

**Pull request merged**
