### PR TITLE
Adding missing desc

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/6591

### CODE REVIEW

**Review by dariomws — APPROVED** [review]

**Comment by tseward** [comment]
Pending on clarification on this one, as well.

**Comment by get-itips** [comment]
> Pending on clarification on this one, as well.

Sorry Trevor, did not understand.

**Comment by get-itips** [comment]
@tseward @dariomws kindly re-review, thanks

**Review by dariomws — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Pull request merged**
