### PR TITLE
Update Export-CsOrganizationalAutoAttendantHolidays.md

### PR DESCRIPTION
**Pull request by CLYVR**
Updating documentation on deprecated cmdlet to remove information on how to use - reference to new cmdlet has been provided.

### CODE REVIEW

**Comment by CLYVR** [comment]
@get-itips @dariomws @tseward @tiburd Please review. Late last year a Caution was added at the top of each of these deprecated cmdlets with reference to the new cmdlets. Now removing the instructions on how to use these deprecated cmdlets.  Will leave this up until the end of CY22Q1 after will further update to remove the pages entirely.  If there are any questions or issues please let me know. THANKS!

**Review by tseward — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by CLYVR** [comment]
@get-itips Sorry to bother you but would appreciate if you can review/approve so these changes can be merged.  Please let me know if you have any questions and thank you!

**Review by get-itips — APPROVED** [review]
@CLYVR Colin thanks for the reminder

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks,

**Pull request merged**
