### PR TITLE
Clarify param not working

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/10688

### CODE REVIEW

**Comment by get-itips** [comment]
@JensTrier

**Comment by JensTrier** [comment]
@get-itips I think also Skip is not working.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
> @get-itips in the past, we've asked the individual to open a support case for what one might consider a bug, rather than making changes to the documentation.

It's true however, I was directed by the Article's author to add that sentence.

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
