### PR TITLE
Edit CsWebServiceConfiguration

### PR DESCRIPTION
**Pull request by aabhasjain-ms**

### CODE REVIEW

**Comment by dariomws** [comment]
@aabhasjain-ms If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=aabhasjain-ms

**Comment by aabhasjain-ms** [comment]
Hii Dario,

Yes these changes are going in next CU for SFB

Thanks,
Aabhas
________________________________

**Review by get-itips — APPROVED** [review]
I am ok once @dariomws suggestions are applied

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Comment by garycentric** [comment]
I've removed the hyphens from headings in these two articles. The hyphen lines don't translate well to docs.microsoft.com.

## Before

image

<br/><br/>

## After

image

**Pull request merged**
