### PR TITLE
Example for MicrosoftTeams and unavailable params

### PR DESCRIPTION
**Pull request by DEberhardt**

### CODE REVIEW

**Comment by DEberhardt** [comment]
New-CsOnlineSession from the Module MicrosoftTeams links here now.
Comparing the command New-CsOnlineSession (Skype) with the Teams variant, a few parameters are not available.
Added a note for each of these.

Also added Example 4 (which would have helped me) establishing a connection to both.
This one may not not be essential (establishing a connection with the command from the Teams module calls Connect-MicrosoftTeams in the background anyway, but running it first enables a semi single-sign-on (Dialog is still shown if logged into more than one Tenant, but no additional credentials are required).

**Comment by DEberhardt** [comment]
Created PR from my fork as I do not have Commit rights from the master branch.
Apologies if this is not the intended way (still familiarising myself more with git)

**Review by get-itips — COMMENTED** [review]
Hello @DEberhardt David. Thanks for your contribution.
The example has been already proposed to another article, see https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6405

And about the parameters not anymore present, they should be removed from the article, as we take the last version of the cmdlet to be the one in sync with the article. What do you think @dariomws @tseward ?

**Review by dariomws — COMMENTED** [review]
Agree with you, @get-itips.

Thank you @DEberhardt for your contribution!

**Comment by tseward** [comment]
@get-itips agreed.

**Comment by yogkumgit** [comment]
@DEberhardt

**Comment by DEberhardt** [comment]
removed 2 parameters, but left Username and Example 4 for now.
how should we proceed?

**Review by dariomws — COMMENTED** [review]
I'm not fully convinced to add this example, and I think we can also remove -Username parameter (but leave it is not an issue for me).

What do you think @get-itips @tseward?

**Comment by get-itips** [comment]
> I'm not fully convinced to add this example, and I think we can also remove -Username parameter (but leave it is not an issue for me).
> 
> What do you think @get-itips @tseward?

While I appreciate David's contribution, my vote is

The example, I think, fits better in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6405 as this repo holds more procedural examples/guides.

To remove all parameters not present in the cmdlet as of today.

**Comment by DEberhardt** [comment]
This should do then.
Example 4 removed, Parameters not present in MicrosoftTeams removed.

**Comment by get-itips** [comment]
David, we are reaching the approval :) 

 are you familiar with [PlatyPS](https://github.com/PowerShell/platyPS) ?

It is telling me that new parameters are present:

```
New-CsOnlineSession [-Credential <PSCredential>] [-OverrideAdminDomain <String>]
 [-OverridePowerShellUri <String>] [-TeamsEnvironmentName <String>] [-SessionOption <PSSessionOption>]
 [<CommonParameters>]
```

**Comment by DEberhardt** [comment]
I know of the beaked Module, but haven't used the PlatyPS yet myself. 😄 

Just double-checked the parameters with Get-help New-CsOnlineSession and corrected the order of the Syntax.
I have 5 Parameters in MicrosoftTeams (v1.1.10-preview)

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks.

**Pull request merged**
