### PR TITLE
Updates to the delegated flow

### PR DESCRIPTION
**Pull request by pbafna03**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by yogkumgit** [comment]
@dariomws @get-itips

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thank

**Comment by yogkumgit** [comment]
@tiburd Gentle reminder. Thanks

**Pull request merged**
