### PR TITLE
Adding link to primary documentation

### PR DESCRIPTION
**Pull request by divyachapan**
I have cleaned up this document and have referenced the primary documentation

### CODE REVIEW

**Comment by get-itips** [comment]
I see the merge has conflicts, it seems the same file was also modified by this _later_ PR https://github.com/MicrosoftDocs/office-docs-powershell/pull/5925

**Comment by dariomws** [comment]
Nothing more to add to @get-itips's comment.

**Comment by tseward** [comment]
Ditto @get-itips @dariomws

**Comment by yogkumgit** [comment]
@divyachapan please update and resolve. Thanks

**Comment by yogkumgit** [comment]
@divyachapan please update and resolve. Thanks

**Comment by yogkumgit** [comment]
@divyachapan please update and resolve. Thanks

**Comment by get-itips** [comment]
So this PR was replaced by https://github.com/MicrosoftDocs/office-docs-powershell/pull/5925 @yogkumgit please close without merging. Thanks

**Pull request closed without merging**
