### PR TITLE
Dariomws1

### PR DESCRIPTION
**Pull request by dariomws306**
I have added a description for ReadReceiptsEnabledType and AllowUrlPreviews parameters.

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@dariomws306 Can you please fix the conflicts so I can get this reviewed and merged.

**Comment by dariomws306** [comment]
@AndreaBarr , done!

**Comment by AndreaBarr** [comment]
@dariomws306 This still has a conflict at the branch level. Please fix this so it can be reviewed.

**Comment by kenwith** [comment]
I updated @dariomws306 branch 'office-docs-powershell' so it has the most recent from master branch. That kicked off a new check.. once it clears I can merge.

**Comment by dariomws306** [comment]
Thank you @Kenwith!

**Pull request merged**
