### PR TITLE
improving detailed

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/7073

### CODE REVIEW

**Review by dariomws — APPROVED** [review]

**Comment by tseward** [comment]
Is there a reason we're using parentheses in the explainer text?

**Comment by get-itips** [comment]
> Is there a reason we're using parentheses in the explainer text?

What do you propose? :)

**Comment by yogkumgit** [comment]
@tseward

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Comment by yogkumgit** [comment]
Gentle reminder, @tseward please review the changes.

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks.

**Pull request merged**
