### PR TITLE
Update New-CsTeamsEmergencyCallRoutingPolicy.md

### PR DESCRIPTION
**Pull request by hbunkradt**
-CarrierProfile "Local" is a wrong parameter on ### Example 1

### CODE REVIEW

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by dariomws — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by JensTrier** [comment]
This PR fixed the issue https://github.com/MicrosoftDocs/office-docs-powershell/pull/8722

**Review by JohanFreelancer9 — APPROVED** [review]

**Pull request closed without merging**
