### PR TITLE
Improving description

### PR DESCRIPTION
**Pull request by get-itips**
The verbiage was taken from https://docs.microsoft.com/en-us/azure/information-protection/log-analyze-usage

@dariomws What do you think?
I could test that definitely the default is not "1" and that specifying 20 seems to consume more Kb/s

Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/7487

### CODE REVIEW

**Comment by tseward** [comment]
@dariomws 20 is the default.

**Review by tseward — APPROVED** [review]

**Comment by get-itips** [comment]
> @dariomws 20 is the default.

Great info

**Comment by dariomws** [comment]
@tseward thanks!

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Comment by tiburd** [comment]
close > reopen

**Pull request merged**
