### PR TITLE
Update multi-language meeting invite control document

### PR DESCRIPTION
**Pull request by Jicwang**
Update multi-language meeting invite control document

### CODE REVIEW

**Comment by pbafna03** [comment]
@Jicwang  - while you are updating these pages, you might want to update the "Applies to:" to include "Microsoft Teams" as well. Assuming these cmdlets are relevant for Teams. 

For e.g. in https://docs.microsoft.com/en-us/powershell/module/skype/grant-cstenantdialplan?view=skype-ps

**Comment by Jicwang** [comment]
Hi @pbafna03 
Thank you for the comments, I updates the file. Could you help review again. Thank you.

**Review by dariomws — APPROVED** [review]

**Comment by Jicwang** [comment]
Hello @tseward @get-itips 
When you have time, could you help review this PR. Thank you.

**Review by get-itips — COMMENTED** [review]
Hello @Jicwang Jasper,
I was working on a draft PR to add this parameter too, among others, but was waiting for SME approval, and in that draft PR I included the list of currently supported language codes, maybe you want to do the same here:

`ar-SA,az-Latn-AZ,bg-BG,ca-ES,cs-CZ,cy-GB,da-DK,de-DE,el-
GR,en-GB,es-ES,es-MX,et-EE,eu-ES,fi-FI,fil-PH,fr-CA,fr-FR,gl-ES,he-IL,hi-IN,hr-HR,hu-HU,id-ID,is-IS,it-IT,ja-JP,ka-GE,k
k-KZ,ko-KR,lt-LT,lv-LV,mk-MK,ms-MY,nb-NO,nl-NL,nn-NO,pl-PL,pt-BR,pt-PT,ro-RO,ru-RU,sk-SK,sl-SL,sq-AL,sr-Latn-RS,sv-SE,t
h-TH,tr-TR,uk-UA,vi-VN,zh-CN,zh-TW.`

**Comment by Jicwang** [comment]
Hello @get-itips
I can do that, do you mind share your draft PR link, I can follow the style. Thank you.

**Comment by get-itips** [comment]
Great @Jicwang noticed you are from Microsoft

If you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/

**Comment by Jicwang** [comment]
Hi @get-itips 
I linked my account. But still don't have the blue label, maybe next PR?  Also I updated the languages list. Thank you for the help.

I need all reviewers approval then I can check in the PR, right?

**Comment by get-itips** [comment]
> Hi @get-itips I linked my account. But still don't have the blue label, maybe next PR? Also I updated the languages list. Thank you for the help.
> 
> I need all reviewers approval then I can check in the PR, right?

not sure @dariomws do you know about that?

**Review by get-itips — APPROVED** [review]

**Comment by Jicwang** [comment]
There is no button for me to complete this PR. I have some deadline for this task.  : ) Thank you again.

**Comment by Jicwang** [comment]
Hi @get-itips @dariomws 
When you have time, could you help merge this PR.  I don't think I have write access for this repository.  Thank you.

**Review by get-itips — APPROVED** [review]

**Comment by Jicwang** [comment]
Thank you for help ; )

**Comment by dariomws** [comment]
@Jicwang @get-itips yes, the tag will appear on the next PR or issue.

**Pull request merged**
