### PR TITLE
Exchange Online Powershell - V3 Module updates - Task 6559839 -draft - Do not merge

### PR DESCRIPTION
**Pull request by Ashok-Lobo**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by chrisda** [comment]
I'm not merging this until this 'version 3' of the EXO module is available.

I'm pretty tuned in to all things EXO V2 module, and I'm currently assisting in making some updates for v2.0.6-Preview8, which is about to come out. I've never heard of V3 before, and we can't publish this until it's somehow announced or is available in the PowerShell Gallery.

**Comment by chrisda** [comment]
I also question the need to have different topics about this. If V2 is truly just a rebranding of the v2.0.6-PreviewX version, which I presume will carry over to the general release of v2.0.6, then it might be better to incorporate the information into the existing V2 topics for search results, reduce duplication of content, etc. I'll need to ponder.

**Comment by JohanFreelancer9** [comment]
> @JohanFreelancer9

@yogkumgit, I'll do a copy review if necessary once a decision has been made about this PR.

**Comment by chrisda** [comment]
OK, we are going the wrong direction here. Way too many new topics. The information is all good, be we should try to incorporate into existing topics wherever possible. Creating a new topic should be a last resort, because it basically sets up search result competition with existing topics.

**Comment by Ashok-Lobo** [comment]
> Docs Build status updates of commit _[19f322c](https://github.com/Ashok-Lobo/office-docs-powershell/commits/19f322cfdbd115f125d6e963586b2750764edb75)_:
> 
> ### ✅ Validation status: passed
> File	Status	Preview URL	Details
> [exchange/docs-conceptual/advantages-of-rest-cmdlets-over-rps.md](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6559839/exchange/docs-conceptual/advantages-of-rest-cmdlets-over-rps.md)	✅Succeeded	[View](https://review.docs.microsoft.com/en-us/powershell/exchange/advantages-of-rest-cmdlets-over-rps?view=exchange-ps&branch=pr-en-us-9871) (exchange-ps)	
> [exchange/docs-conceptual/app-only-auth-powershell-v2.md](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6559839/exchange/docs-conceptual/app-only-auth-powershell-v2.md)	✅Succeeded	[View](https://review.docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps&branch=pr-en-us-9871) (exchange-ps)	
> [exchange/docs-conceptual/breaking-feature-announcements.md](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6559839/exchange/docs-conceptual/breaking-feature-announcements.md)	✅Succeeded	[View](https://review.docs.microsoft.com/en-us/powershell/exchange/breaking-feature-announcements?view=exchange-ps&branch=pr-en-us-9871) (exchange-ps)	
> [exchange/docs-conceptual/cmdlets-disabled-withdrawn.md](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6559839/exchange/docs-conceptual/cmdlets-disabled-withdrawn.md)	✅Succeeded	[View](https://review.docs.microsoft.com/en-us/powershell/exchange/cmdlets-disabled-withdrawn?view=exchange-ps&branch=pr-en-us-9871) (exchange-ps)	
> [exchange/docs-conceptual/media/get-connection-info-v3.png](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6559839/exchange/docs-conceptual/media/get-connection-info-v3.png)	✅Succeeded	[View](https://review.docs.microsoft.com/en-us/powershell/exchange/new-upcoming-cmdlets-releases?view=exchange-ps&branch=pr-en-us-9871) (exchange-ps)	
> [exchange/docs-conceptual/new-upcoming-cmdlets-releases.md](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6559839/exchange/docs-conceptual/new-upcoming-cmdlets-releases.md)	✅Succeeded	[View](https://review.docs.microsoft.com/en-us/powershell/exchange/new-upcoming-cmdlets-releases?view=exchange-ps&branch=pr-en-us-9871) (exchange-ps)	
> [exchange/docs-conceptual/overview-exchange-online-powershell-v3.md](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6559839/exchange/docs-conceptual/overview-exchange-online-powershell-v3.md)	✅Succeeded	[View](https://review.docs.microsoft.com/en-us/powershell/exchange/overview-exchange-online-powershell-v3?view=exchange-ps&branch=pr-en-us-9871) (exchange-ps)	
> [exchange/docs-conceptual/toc.yml](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6559839/exchange/docs-conceptual/toc.yml)	✅Succeeded	[View](https://review.docs.microsoft.com/en-us/powershell/exchange/advantages-of-rest-cmdlets-over-rps?view=exchange-ps&branch=pr-en-us-9871) (exchange-ps)	
> For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209081643339962-9871/BuildReport?accessString=5b384184acf31ca57c2118bd95c25b4bffd6f4e73942e6e179b09c3fa52cd1a4).
> 
> **Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).
> 
> For any questions, please:
> 
> * Try searching the docs.microsoft.com [contributor guides](https://review.docs.microsoft.com/en-us/help/?branch=main)
> * Post your question in the [Docs support channel](https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47)

Thank you for letting me know about this. There won't be any new topics. The next task is to update the existing topics.
Thank you for fixing the warnings.

**Comment by Ashok-Lobo** [comment]
@chrisda 
Thank you for letting me know about this. There won't be any new topics. The next task is to update the existing topics. Thank you for fixing the warnings.

**Comment by chrisda** [comment]
OK. Be advised that I've done my version of the changes in this branch here:

https://github.com/MicrosoftDocs/office-docs-powershell/blob/ExOV3-chrisda/exchange/docs-conceptual/exchange-online-powershell-v2.md

**Pull request closed without merging**
