### PR TITLE
Update Set-CsOnlineLisCivicAddress.md

### PR DESCRIPTION
**Pull request by SimranGarg898**
Hello Team, 
I did a repro for the same command and using the Set-CsOnlineLisCivicAddress we are able to edit the validated addresses as well. Though this is still not achievable from the TAC directly but this powershell command can be used.
image
'test' is a validated emergency address

image
I am able to make the changes to street name from 'back street' to 'front street' using powershell

image
The change reflects in the TAC as well.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by yogkumgit** [comment]
@get-itips @tseward @dariomws

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
Hello @SimranGarg898 
Thanks for your contribution. I could reproduce, however, I am not sure if that is intended, I'll try to confirm with the Team,
What version of the Teams PowerShell did you use?
Thanks

**Review by dariomws — COMMENTED** [review]
Agree with @get-itips, I think it's not intended.

I also tested it and could change it from PS, but if you try from the TAC:
image

It's also documented here:
https://docs.microsoft.com/microsoftteams/add-change-remove-emergency-location-organization

**Comment by pbafna03** [comment]
> @pbafna03 Can you help us confirm if this is the intended behavior? Thanks

Looping in @vivekiiit to comment on this

**Comment by yogkumgit** [comment]
@vivekiiit Gentle reminder

**Comment by yogkumgit** [comment]
@pbafna03 Please suggest how to proceed. Thanks

**Comment by pbafna03** [comment]
Had a side chat with @vivekiiit, this cmdlet has been recently updated so we can edit the addresses. However not all fields are editable. @vivekiiit's team will update the documentation with fields that can be edited.

**Comment by yogkumgit** [comment]
@pbafna03 Shall we keep it open or close the PR. Kindly suggest.

**Comment by pbafna03** [comment]
Probably abandon this one and wait for @vivekiiit's to open a new one with proper details.

**Pull request closed without merging**
