### PR TITLE
[HOLD] ECC LiveSite Update Get-CalendarDiagnosticObjects.md

### PR DESCRIPTION
**Pull request by telaws**
Customers are unable to take logging output from Get-CalendarDiagnosticLog and convert valid output from Get-CalendarDiagnosticAnalysis, the latter is broken is EXO and results in a Watson OutOfRange error, open active bug linked.

Tenant Admins only workaround is to use Get-CalendarDiagnosticObjects, but by default they will only get 63 out of the 220+ available properties. 

Extra properties can be entered via the CustomPropertyNames parameter, however they are not publicly documented
Attached file has Values and Descriptions:
Excluding deprecated values for NetMeeting and those that returned InvalidSchemaProperty, requires review:
CustomProperyNameValuesAndDescriptions_ContentIdeaSubmission.csv
Shane Ferrell EEE from Calendaring Platform recommended Rob Whaley as a writer to get these updated in documentation.
See Attached email in files
RE VSO 1550318 - 193709351 - Customer Escalation Ask  Get-CalendarDiagnosticObjects - Discovering StoreProps for CustomPropertyNames.msg

Per Shane Ferrell we also need to add updates for these, or would this be a different request ? See attached email
Also need to update the Get-CalendarDiagnosticObjects documentation with regards to new parameters: 
-ShouldFetchAttendeeCollection, -EwsID, -ConfigurationName

### CODE REVIEW

**Comment by telaws** [comment]
Please reach out to scorrea@microsoft.com or telaws@microsoft.com for any questions or concerns.  Attachment files containing values and descriptions for additional StoreProps can be seen in https://dev.azure.com/contentidea/ContentIdea/_workitems/edit/121547

**Comment by yogkumgit** [comment]
@chrisda Please review and merge this PR. Thanks

**Comment by chrisda** [comment]
@telaws, the area of the topic where you made the addition is standard boilerplate across ALL cmdlet topics, so I don't want to customize it in any way. I moved your changes to the DESCRIPTION area of the topic.

**Comment by chrisda** [comment]
Closing in favor of #6290, which adds the missing parameters, although without descriptions.

**Pull request closed without merging**
