### PR TITLE
Update Set-CsConferencingConfiguration.md

### PR DESCRIPTION
**Pull request by Ravindra-Microsoft**
Added parameter EncryptArchivedData - Boolean flag to turn on/off encryption for a conference’s archived attachments.
Refer related VSO item https://skype.visualstudio.com/SBS/_workitems/edit/2299896

### CODE REVIEW

**Comment by Ravindra-Microsoft** [comment]
@MicrosoftDocs/marveldocs-pubops PR is ready for review. Please review and publish.

**Review by dariomws — APPROVED** [review]
Approve, but I don't have an SfB 2019 lab to test it.

**Review by get-itips — APPROVED** [review]
Hello @Ravindra-Microsoft how are you? Hope you are doing good.
I am afraid we do not have access to that vso resource, can you kindly confirm if this update is going live on the next CU? installed the March 2021 and the parameter seems to not be there.
Thank you

**Comment by Ravindra-Microsoft** [comment]
Hi Andreas,

Yes this is for Sfb2019 Cu6.

***@***.***D73250.B1A9B2A0]

Thanks.

Regards,
Ravindra Singh Bisht
Mobile: +91-9711729996

**Comment by Kateyanne** [comment]
@get-itips see Ravindra's comment above. Let me know when this is ready to be merged.

**Comment by get-itips** [comment]
> @get-itips see Ravindra's comment above. Let me know when this is ready to be merged.

It's ready, thanks

**Pull request merged**
