### PR TITLE
Update Grant-CsTeamsUpgradePolicy.md

### PR DESCRIPTION
**Pull request by revaldiv**
Lines 42 and 43 identity needs to include AndMeetings (SfBWithTeamsCollabAndMeetings and SfBWithTeamsCollabAndMeetingsWithNotify) the present document duplicates SfBWithTeamsCollab and SfBWithTeamsCollabWithNotify identities for the meeting modes.  I changed to accurately reflect the proper identities.

### CODE REVIEW

**Comment by kenwith** [comment]
@tomkau and @islubin - Just wanted to confirm if this change is OK to merge? Looks OK to me. 

@revaldiv - thanks for taking the time to make the docs better, much appreciated!

**Comment by islubin** [comment]
@bjwhalen as owner of upgrade to review

**Comment by bjwhalen** [comment]
Thanks for looping me in @islubin 

The change looks good. this was a bug in a change I made when I added the sfbwithTEamsCollabAndMeetings modes.  I added the rows to the table and the modle column is correct but I mistakenly didn't update the identity name.

**Comment by kenwith** [comment]
Thanks everyone!

**Pull request merged**
