### PR TITLE
Remove -confirm parameter

### PR DESCRIPTION
**Pull request by michbrown-png**
-confirm is no longer a parameter then we need to update Start-CsExMeetingMigration

### CODE REVIEW

**Review by dariomws — CHANGES_REQUESTED** [review]
@michbrown-png, please remove it from the syntax section.

Will it be removed in the next CU? I still see it on a server with the latest SU (May 2021 - 2046.369).

Start-CsExMeetingMigration doesn't have Confirm parameter on this server.

Thanks!

**Review by get-itips — CHANGES_REQUESTED** [review]
agree with @dariomws suggestions

**Review by michbrown-png — COMMENTED** [review]
Removed references to confirm in documentation

**Comment by get-itips** [comment]
> Will it be removed in the next CU? I still see it on a server with the latest SU (May 2021 - 2046.369).

@michbrown-png Can you kindly answer @dariomws 's question here? Thank you!

**Comment by michbrown-png** [comment]
@get-itips @dariomws @pupara It is already removed in the latest PowerShell Module release.

**Pull request merged**
