### PR TITLE
Patch 9

### PR DESCRIPTION
**Pull request by dariomws306**
@kenwith @tomkau 

I don't know what "-RouteType" parameter do on New-CsOnlineVoiceRoutingPolicy and Set-CsOnlineVoiceRoutingPolicy.
Could you help me with this? Or should I use "This parameter is reserved for internal Microsoft use"?

Also, I am thinking that I should have write more information about that these cmdlets are related to Teams Direct Routing. What do you think?

Thanks!

### CODE REVIEW

**Comment by kenwith** [comment]
@tomkau - OK to merge?

**Comment by tomkau** [comment]
@dariomws306 -- from what I can see in code, the parameter -RouteType is not used.  Let's use your suggestion of saying reserved for internal Microsoft use.

There is already good documentation for direct routing, so we do not need to add a lot of details about direct routing in the cmdlet documentation.  But, for the relevant cmdlets, it's good to note that they are used to configure direct routing.  Admins can then look up more details as needed.

For the relevant cmdlets, we can add something simple like:

"This cmdlet is used when configuring Microsoft Phone System Direct Routing."  

I'm not very familiar with direct routing and how to configure, but if you read this article it should help you identify which are used with dircet routing configuration.
https://docs.microsoft.com/en-us/MicrosoftTeams/direct-routing-configure

**Comment by dariomws306** [comment]
@tomkau thanks!!

I have been using the DR article you sent me and onpremises cmdlets as referece because they are very similar.

I have applied all the comments/details you sent me.

**Comment by dariomws306** [comment]
@kenwith @tomkau do you think we are done with this?

**Comment by tomkau** [comment]
Yes, let's go ahead and push these.

**Pull request merged**
