### PR TITLE
Update Set-CsOnlineVoicemailUserSettings.md

### PR DESCRIPTION
**Pull request by vijurtse**
deprecating this option from the 1st of June

### -OofGreetingFollowCalendarEnabled
The OofGreetingFollowCalendarEnabled parameter represents whether to play out-of-office greeting in voicemail deposit scenario when user set out-of-office in calendar.

```yaml
Type: System.Boolean
Parameter Sets: (All)
Aliases: 
applicable: Microsoft Teams

Required: False
Position: Named
Default value: None
Accept pipeline input: False
Accept wildcard characters: False
```

### CODE REVIEW

**Comment by vijurtse** [comment]
deprecating this option

### -OofGreetingFollowCalendarEnabled
The OofGreetingFollowCalendarEnabled parameter represents whether to play out-of-office greeting in voicemail deposit scenario when user set out-of-office in calendar.

```yaml
Type: System.Boolean
Parameter Sets: (All)
Aliases: 
applicable: Microsoft Teams

Required: False
Position: Named
Default value: None
Accept pipeline input: False
Accept wildcard characters: False
```

**Comment by vijurtse** [comment]
Deprecating this option
### -OofGreetingFollowCalendarEnabled
The OofGreetingFollowCalendarEnabled parameter represents whether to play out-of-office greeting in voicemail deposit scenario when user set out-of-office in calendar.

```yaml
Type: System.Boolean
Parameter Sets: (All)
Aliases: 
applicable: Microsoft Teams

Required: False
Position: Named
Default value: None
Accept pipeline input: False
Accept wildcard characters: False
```

**Comment by michbrown-png** [comment]
@vijurtse - Was the functionality removed from the Teams Powershell Module?

**Comment by vijurtse** [comment]
Yes it has been removed, please approve the PR @michbrown-png

**Pull request merged**
