### PR TITLE
Update Get-SPOSite.md

### PR DESCRIPTION
**Pull request by WayneEwington**
Covered the scenario that if the -Limit parameter is provided, then some site collection properties are not populated and may contain default values.

### CODE REVIEW

**Review by get-itips — APPROVED** [review]
I am ok with the change, the only thing I could ask is removing the NOTE markdown tag with a regular note...

**Review by dariomws — APPROVED** [review]
Agree with @get-itips.

**Comment by tseward** [comment]
Ditto @get-itips.

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please  merge this PR. Thanks.

**Pull request merged**
