### PR TITLE
Update Set-CsPhoneNumberAssignment.md

### PR DESCRIPTION
**Pull request by JensTrier**
Fixed numbers in example

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by dariomws — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Comment by yogkumgit** [comment]
@tseward  please review

**Comment by JensTrier** [comment]
@yogkumgit I did one more update to the file. Please have a look

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
