### PR TITLE
Update Remove-TeamUser.md

### PR DESCRIPTION
**Pull request by AlexanderHolmeset**
Needed to specify user role to remove.  Docs also says that -Role is only used to demote user, but -role removes the user from the team, as pr cmd description at the top.

### CODE REVIEW

**Comment by kenwith** [comment]
@AlexanderHolmeset - thanks for taking the time to make the docs better and submit fixes. It is much appreciated!

@islubin - can you let me know if ok to merge?

**Comment by yogkumgit** [comment]
@dariomws306  , @get-itips and @tseward Please review this PR and give your feedback. @kenwith looks forward to your comments.

**Comment by get-itips** [comment]
Hello @AlexanderHolmeset how are you?

I tested this in my lab, and I could verify that if you ran

`Remove-TeamUser -GroupId 31f1ff6c-d48c-4f8a-b2e1-abca7fd399df -User dmx@example.com -Role Owner`

it actually removes the ability for the user, to access the team, but, strange enough, if you ran

`Get-TeamUser  -GroupId 31f1ff6c-d48c-4f8a-b2e1-abca7fd399df `

you will see it still listed in the Powershell result, but as a member (as the current article says)

image

(You won't see it listed in the Teams UI though)

Maybe is some caché thing or the module is buggy, either way, it seems it is better to describe the current behavior of the cmdlet, as you suggest in this pr, so I'll accept it.

**Comment by tseward** [comment]
We should see if the PG considers this a bug prior to changing the article. As the module itself has [-Role] as _optional_, the PR would change the article and the product would no longer match the documentation.

**Comment by get-itips** [comment]
@tseward you are right on that. thanks

**Comment by dariomws306** [comment]
There is a similar behaviour with Add-Teamuser (and different from Admin Center):
https://github.com/MicrosoftDocs/office-docs-powershell/issues/1665

I have done some testing and I found that the -Role paramater didn't exist in older version of Teams Powershell.

I am agree with Trevor, also I think it makes sense that this parameter is optional.

**Comment by AlexanderHolmeset** [comment]
Here is a screenshot to better describe the error at my end. 
The difrence between my and @get-itips error, is that with me the user is removed and not demoted.
So probably some kind of bug in the module.
Makes sense as you say to make the parameter -Role optional. 
Maybe there should be a new cmdlet like this to demote/promote users:
Set-TeamUser -GroupID "XXXXXXX" -User "user1@contoso.com" -Role Owner

image

**Comment by erwinbierens** [comment]
> Here is a screenshot to better describe the error at my end.
> The difrence between my and @get-itips error, is that with me the user is removed and not demoted.
> So probably some kind of bug in the module.
> Makes sense as you say to make the parameter -Role optional.
> Maybe there should be a new cmdlet like this to demote/promote users:
> Set-TeamUser -GroupID "XXXXXXX" -User "[user1@contoso.com](mailto:user1@contoso.com)" -Role Owner
> 
> image

This only applies to the owner role.. 

When you add/remove the user as a member this error is not displayed. 
image

**Comment by AlexanderHolmeset** [comment]
Good catch Erwin.

**Comment by kenwith** [comment]
@islubin can you comment on this one? Is this a bug and should be change the documentation?

**Comment by kenwith** [comment]
Add Jamie Stark ( @nomorephones ) who took over Teams PowerShell from @islubin to review and sign off.

**Comment by modpra** [comment]
Any updates on this? The PowerShell to remove users still does not work.

**Comment by kenwith** [comment]
@nomorephones any update?

**Comment by get-itips** [comment]
Tested this again with module version 1.0.1

Removed user that was owner on a group using the -Owner parameter, **and it was demoted to member.** This was reflected right away both in UI and Powershell Get-TeamUser cmdlet.

Removed user that was owner on a group NOT using the -Owner parameter, **and it was removed from the channel/group.** This was NOT reflected right away in Powershell Get-TeamUser cmdlet, and I am still waiting to see this reflected.

**Comment by dariomws306** [comment]
Also tested with 1.0.1, my comments:

- Same as Andres using -Role parameter (if I use user UPN or UserId)
- Without -Role parameter:
  * If I use UserId same as Andres, user is not removed from the Team, not demoted to member and 
    no output
  * If I use UPN same as Erwin, I get the same error

Cmdlet documentation says that we should use UPN.

**Comment by get-itips** [comment]
@tseward what do you think of our conclusions ?

**Comment by tseward** [comment]
@get-itips we're still on hold for this one.

**Comment by get-itips** [comment]
@AlexanderHolmeset Can you test again with module version 1.0.1 ? Thanks

**Comment by AlexanderHolmeset** [comment]
@get-itips have the same result as you now
image

**Comment by get-itips** [comment]
Hello @nomorephones 
Issue creator now experiences the same as we all do.
Based on that, and the current behavior of the cmdlet, do you think is necessary to update the documentation?
We really appreciate your time to review this and give us your thoughts.
Thank you

**Comment by kenwith** [comment]
Merging this based on feedback from the product team and they have also added an internal work item to address the inconsistencies brought up above.

**Comment by flowt-au** [comment]
This is still an issue, I think. Using v1.0.21
I have a Team with 1 existing owner. I add a new Owner: 

`Add-TeamUser -GroupId 557acb93-6e5d-4031-8def-xxxxxxxxx -User sally.student@xxxxx.nsw.edu.au -Role Owner`

and I can see Sally as an owner of the group. All good.
Then, if I attempt to demote her to Member as per docs:

`Remove-TeamUser -GroupId 557acb93-6e5d-4031-8def-xxxxxxxxx -User sally.student@xxxxx.nsw.edu.au -Role Owner`

Sally is removed from the Team altogether.
:-(

**Pull request merged**
