### PR TITLE
Update New-LabelPolicy.md

### PR DESCRIPTION
**Pull request by neha-dahiya**
Added EnableAudit in Advanced Settings, this setting is now supported in built-in labeling.

Review Request - @cabailey @MikePaer-MSFT

### CODE REVIEW

**Comment by cabailey** [comment]
@neha-dahiya   Looks great! Only minor quibble is whether really need the words "minimum version" now we have the plus symbol (says the same thing).  Are you able to edit this in the existing PR?

**Comment by neha-dahiya** [comment]
> @neha-dahiya Looks great! Only minor quibble is whether really need the words "minimum version" now we have the plus symbol (says the same thing). Are you able to edit this in the existing PR?

@cabailey I will create a new one and fix it, looks like these PRs merged automatically.

**Comment by neha-dahiya** [comment]
@cabailey - Do you have a preference between Windows (version 2201+) and Windows (2201+)?

**Comment by cabailey** [comment]
@neha-dahiya  Originally, I was going to suggest just "Windows (2201+)" etc for brevity & to avoid word repetition.  But now I see it in context I think it probably does need the word "version" in there each time for clarity.

**Comment by cabailey** [comment]
@neha-dahiya  This one needs the example updating for the relevant cmdlet - (New-LabelPolicy, not Set-LabelPolicy).  Fell into the same trap as I did but Mike's sharp eyes noticed ;)  Before signing off, can you update it and all the other examples so they match the cmdlet for the page?  Thank you!

**Comment by neha-dahiya** [comment]
> @neha-dahiya This one needs the example updating for the relevant cmdlet - (New-LabelPolicy, not Set-LabelPolicy). Fell into the same trap as I did but Mike's sharp eyes noticed ;) Before signing off, can you update it and all the other examples so they match the cmdlet for the page? Thank you!

@cabailey I think I got them all but please take a look one more time.

**Comment by cabailey** [comment]
Looks great - thanks for fixing these other examples!
#sign-off

**Comment by yogkumgit** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

**Pull request merged**
