### PR TITLE
Update New-CsTenantNetworkSite.md

### PR DESCRIPTION
**Pull request by hbunkradt**
-OnlineVoiceRoutingPolicy is the wrong parameter to assign a EmergencyCallRoutingPolicy for a Networksite. Edit Example 1 to EmergncyCallRoutingPolicy

### CODE REVIEW

**Comment by hbunkradt** [comment]
Example 1 -OnlineVoiceRoutingPolicy has to be changed to EmergencyCallRoutingPolicy.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips @dariomws @tseward

**Review by dariomws — COMMENTED** [review]
Thanks for your contribution.

Could you explain this PR a bit more in detail? Example 1 or 2? I think the description does not mention emergency calling.

**Comment by hbunkradt** [comment]
You need to configure through New-CSTenantNetworksite the assignement of the EmergencyCallRoutingPolicy in Teams. OnlineVoiceRoutingPolicy is no longer a parameter on this PS command. Also the Syntax should be correct and OnlineVoiceRoutingPolicy should be removed. Its no longer abailable in Teams module ver. 4.7.0

**Comment by yogkumgit** [comment]
@hbunkradt Gentle reminder.

**Comment by yogkumgit** [comment]
Closing as there is no response. Please feel free to create a new PR for revised update. Thanks

**Pull request closed without merging**
