### PR TITLE
Update New-CsAutoAttendantMenuOption

### PR DESCRIPTION
**Pull request by andyqiu-microsoft**
Update New-CsAutoAttendantMenuOption to include ToneStar and TonePound as dtmf response. This is a new feature that is about to GA next week.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by yogkumgit** [comment]
@dariomws @get-itips @tseward

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
