### PR TITLE
Update Get-CsOnlineUser.md

### PR DESCRIPTION
**Pull request by isrumnon**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by dariomws — COMMENTED** [review]
@isrumnon, it doesn't work to me:

image

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
@isrumnon  I experience the same as @dariomws (using version 4.4.1)

**Comment by yogkumgit** [comment]
@isrumnon

**Comment by isrumnon** [comment]
Corrected the change @yogkumgit

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @get-itips

**Comment by yogkumgit** [comment]
@get-itips

**Review by get-itips — APPROVED** [review]

**Pull request merged**
