### PR TITLE
Separating Skype for business Onprem and Microsoft Teams cmdlet documentation

### PR DESCRIPTION
**Pull request by amareshbAtMicrosoft**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Comment by traya1** [comment]
Hi @[amareshbAtMicrosoft](https://github.com/amareshbAtMicrosoft),

Are you working with a MARVEL writer or team for this work?

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by JohanFreelancer9** [comment]
@yogkumgit, I'm awaiting a reply to @traya1's question before I proceed with the copy review. Thanks.

**Comment by dstrome** [comment]
@amareshbAtMicrosoft This PR is too large and contains too many dissimilar changes for us to properly review it. Please re-submit this as multiple PRs with no more than 30 files per PR. Please try not to mix change types in PRs. For example, if you have bulk changes to add or remove a note, group those changes in a PR without other types of changes. 

Please also make sure your fork is up to date with the current main branch when you submit PRs, and make sure you apply changes to your fork regularly while the PRs are open. This will help reduce the number of conflicts that may happen.

**Pull request closed without merging**
