### PR TITLE
Wording on example 2

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/6498

### CODE REVIEW

**Comment by tseward** [comment]
@get-itips "Per-user" is defined at https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-in-teams. I do not believe any changes should be made to this article.

**Review by dariomws — COMMENTED** [review]
Agree with @tseward.

**Comment by get-itips** [comment]
Ok, thanks for your review, leaving "as is".

**Comment by get-itips** [comment]
@Kateyanne please close without merging.

**Pull request closed without merging**
