### PR TITLE
Update Get-CsUserPolicyAssignment.md

### PR DESCRIPTION
**Pull request by Systems-Liam**
Added some clarification for the practical use of the command for users with less knowledge

### CODE REVIEW

**Review by get-itips — COMMENTED** [review]
Thanks for your contribution @Systems-Liam , I am not sure if the best would be to put this under -Identity description what do you think @tseward @dariomws ?

**Review by dariomws — COMMENTED** [review]
Thanks @Systems-Liam!

@get-itips agree, I think it would be better to put it under -Identity description. Maybe some like the following sentence is enough:
"The identity of the user whose policy assignments will be returned. You can use the user principal name or ObjectId."

Something else important to notice is that if you put an invalid value you get:
"Get-CsUserPolicyAssignment : Invalid input parameters  MOD Administrator needs to be either Guid or Sip address"

**Comment by tseward** [comment]
@dariomws I agree. This would be the common pattern that it simply specifies the type of values it accepts. In general, I wouldn't cross modules, e.g. I wouldn't have an example that calls Get-AzureADUser followed by a Teams/SfB cmdlet.

**Comment by Systems-Liam** [comment]
Thanks for looking into my changes. This is the first time I have edited an article so please bare with me. 

Just wanted to add some quick context, while I agree with the comments on the modifications so far, my motivation for the edit was the junior members of the team really struggled to understand ObjectID, what it referenced and how to use it. I agree not including Get-AzureADUser is a sensible step but equally, the information included was slightly geared up to those less technically able but keen to learn. 

Thanks all, its nice to feel I am finally able to give back to the community after so many years of being the reader!

**Comment by dariomws** [comment]
@Systems-Liam

First of all, thank you so much for your contribution. I hope it's the first of several more.

Although I understand your perspective, I believe that an object's ID or GUID is essential for everyone working in IT.

Again, I'll approve it if you leave a simple sentence under the parameter description to show the possible values.

**Review by get-itips — APPROVED** [review]

**Comment by Systems-Liam** [comment]
Hi @dariomws, thanks for the message, sorry for my initial confusion here, I opened my account specifically to modify this article (and hopefully contribute to others) so I didn't realise you needed me to change the changes I had made already. 

I have now done this, I hope its more in keeping with the standard Microsoft Docs format but if you need me to modify further then please do let me know. 

Thanks!

**Review by tseward — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by dariomws** [comment]
Thank you again @Systems-Liam!

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks.

**Pull request merged**
