### PR TITLE
Adding new-csonlinesession to this index

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/6998

### CODE REVIEW

**Comment by tseward** [comment]
@get-itips for clarity, are you intending to reference a cmdlet in the Teams cmdlet index that is not within this module?

**Comment by get-itips** [comment]
> @get-itips for clarity, are you intending to reference a cmdlet in the Teams cmdlet index that is not within this module?

It is now in this module, it was ported to Teams module. But the article will remain on the Skype folder (at least that was done in the past)

**Review by tseward — APPROVED** [review]

**Comment by DEberhardt** [comment]
We should add a note to the Link that the Teams variant is slightly different (i.E. missing the Username parameter), otherwise people might get confused.

**Comment by yogkumgit** [comment]
@dariomws

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks.

**Pull request merged**
