### PR TITLE
Updating param desc

### PR DESCRIPTION
**Pull request by get-itips**
@dariomws can you kindly test on your tenant? I appreciate

Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/7036

### CODE REVIEW

**Review by dariomws — APPROVED** [review]
Tested, no effect.

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne

**Comment by dariomws** [comment]
Hi @garycentric, I see you are formatting the notes in several cmdlets. We weren't doing it because Get-Help doesn't render it. Please, could you let us know if you have different or new information? Maybe we should start formatting them.

Thank you!

**Comment by garycentric** [comment]
@dariomws 

> Hi @garycentric, I see you are formatting the _note_s in several cmdlets. We weren't doing it because Get-Help doesn't render it. Please, could you let us know if you have different or new information? Maybe we should start formatting them.

My edits are based on [review criteria](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master) and appearance on [docs.microsoft.com](https://docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps). If doing so is a problem for delivering docs via **Get-Help**, I need to hear about that.

**Comment by chrisda** [comment]
There was a bug where Alert formatting in the SYNOPSIS section wasn't working; I'm not sure if they ever fixed this. It has always worked in the DESCRIPTION section; not sure about within individual parameter descriptions.

I've just been doing basic formatting like this:

**Note**: Blah, blah, blah.

Either way, whatever formatting you do in the topics on the web (with the exception of bulleted lists) is completely lost when the topics are converted into MAML XML for help at the command line.

**Pull request merged**
