### PR TITLE
Update Add-SPOGeoAdministrator.md

### PR DESCRIPTION
**Pull request by expiscornovus**
Changed the syntax. It looks like it was the syntax of site designs. Also changed the code example and the parameters.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Simon, appreciated.

**Comment by expiscornovus** [comment]
@VesaJuvonen, no problem. Btw, my name is Dennis ;)

**Comment by VesaJuvonen** [comment]
Wow - "Simon"... I was multi-tasking, so sorry for that.

**Comment by expiscornovus** [comment]
@VesaJuvonen no problem. Sometimes I have that too :)

**Pull request merged**
