### PR TITLE
Add documentation for all TeamsComplianceRecording cmdlets

### PR DESCRIPTION
**Pull request by aditdalvi**
Add documentation for all TeamsComplianceRecordingPolicy cmdlets.
This includes CsTeamsComplianceRecordingPolicy cmdlets and CsTeamsComplianceRecordingApplication cmdlets.

Update TOC in skype.md.

### CODE REVIEW

**Comment by kenwith** [comment]
@aditdalvi - thank you for the content additions. If you don't mind, if you are part of the product team, if you would please link your GitHub account to your Microsoft account so that the system adds a blue "Microsoft submitter" label to the PR automatically. It helps us keep track of where PR's are coming from and up to date on all the great work you and your team are doing. Guidance on how to do this is here: https://docs.opensource.microsoft.com/tools/github/index.html 

I added @brandber as a reviewer as he is the point of contact for all Teams PowerShell.

Thanks for the PR!

**Comment by aditdalvi** [comment]
Thanks @kenwith I was gonna reach out to on how to get the "Microsoft submitter" label but you beat me to it :)

**Comment by aditdalvi** [comment]
Thanks for the comments! I'll make the changes asap.

Sorry, I forgot to upload the documentation for New-CsTeamsComplianceRecordingPairedApplication. Thanks for catching that!

**Comment by aditdalvi** [comment]
Thanks for completing the pull request @kenwith!

I'm still not sure why the "Microsoft submitter" label is missing; I've gone through the setup steps you provided. Hopefully it shows up in any future pull requests.

**Comment by aditdalvi** [comment]
Also, I'm curious: How long does it typically take for the documentation to show up on docs.microsoft.com?

**Comment by kenwith** [comment]
The docs.microsoft.com site pulls content from the 'live' branch.. so there is a step required to merge the 'master' branch to the 'live' branch. I just did that though so it should show live shortly.. it seems to take about 20 minutes from when the master to live is merged before it starts showing on docs.microsoft.com and I think it is from some caching in place.

**Pull request merged**
