### PR TITLE
Improved inaccurate description

### PR DESCRIPTION
**Pull request by frankpeng7**
Customers have had doubt about the "internal user only" description and hesitated to use it. The description was wrong and needs to be updated.

### CODE REVIEW

**Review by dariomws — COMMENTED** [review]
Not sure about this...

@frankpeng7 did you test it? It seems that it does not work as expected for me:
image
(Grady had this policy assigned)

Even if I wait several minutes, I don't see the policy applied to everyone. I think it still applies the Global policy for them.

**Review by get-itips — COMMENTED** [review]
This was discussed recently [here](https://github.com/MicrosoftDocs/office-docs-powershell/pull/7646#pullrequestreview-645148540) @frankpeng7 Frank, can you kindly provide the exact version of the Teams Ps module you are using to test this? Thanks

**Comment by frankpeng7** [comment]
@get-itips I'm using module `MicrosoftTeams 2.3.1`

**Comment by frankpeng7** [comment]
@dario-ms Assigning the policy to tenant-level won't write to the per-user configuration. It means when the per-user ApplicationAccessPolicy config is empty, tenant-level/Global config will take effect.
image

**Comment by frankpeng7** [comment]
If you want the per-user config to be updated you'll need to run `Get-CsOnlineUser | Grant-CsApplicationAccessPolicy -PolicyName "ASimplePolicy"` instead of using the `-Global` flag.

**Comment by frankpeng7** [comment]
@get-itips As the eng owner of this cmdlet I'm asking you to please revert #7646 because the E2E works as described. I was not notified of the change otherwise I'd have called it out. I noticed this recently because we've got a few customers complaints about this.

**Comment by get-itips** [comment]
> @get-itips As the eng owner of this cmdlet I'm asking you to please revert #7646 because the E2E works as described. I was not notified of the change otherwise I'd have called it out. I noticed this recently because we've got a few customers complaints about this.

Thanks for mentioning that. I do not have the required permissions to approve/revert PRs however I'll approve this one. 👍

**Review by get-itips — APPROVED** [review]

**Comment by frankpeng7** [comment]
@get-itips thanks for the ship-it. I've deleted the inaccurate part of #7646 and combine it with this change. Please help merge it when you can. Thanks!

**Comment by yogkumgit** [comment]
@tseward

**Comment by frankpeng7** [comment]
Hey @yogkumgit @tseward do you know who can help merge this? Thanks!

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@Kateyanne Please merge this PR. Thanks

**Pull request merged**
