### PR TITLE
Improves LegacyAuthProtocolsEnabled documentation

### PR DESCRIPTION
**Pull request by koskila**
Fixes a misleading description in the documentation for -LegacyAuthProtocolsEnabled, adds an example and expands the documentation.

Fixes this issue:
#1994

### CODE REVIEW

**Comment by koskila** [comment]
Not sure what breaks the build. It's waiting for a level 3 header, but I added a level 4 header (under a level 3 one) - that's not allowed?

Please advice, how to fix this. Thanks!

**Comment by kenwith** [comment]
@koskila - it is the schema that is very picky. Even adding different headings than it expects it will complain like this. Here is the schema it is testing against: https://github.com/PowerShell/platyPS/blob/master/platyPS.schema.md

**Comment by kenwith** [comment]
@koskila - I think I was able to make the schema happy with adjusting the headings. Thanks for the effort on this to make the docs better.

@VesaJuvonen - Changes look ok to merge?

**Comment by VesaJuvonen** [comment]
Looks good, except the Example is in a wrong location and not under Examples. I'll merge this and then update it accordingly before pushing like. Thx @koskila for the contribution.

**Comment by koskila** [comment]
@VesaJuvonen I was wondering about the logic for the examples.. Thanks!

@kenwith Thanks for the fix, didn't get around to look into it myself yet!

**Pull request merged**
