### PR TITLE
Remove ShowInTeamsSearchAndSuggestions

### PR DESCRIPTION
**Pull request by dilip-2201**
Remove switch: Remove ShowInTeamsSearchAndSuggestions
Private Team Discoverabilty feature was dropped and this switch ShowInTeamsSearchAndSuggestions is no longer relevant.
Official Microsoft Docs are removed for the Private Team discoverabilty feature. but there is still reference in the above PS doc.

MVP Blog: https://tomtalks.blog/2020/11/microsoft-teams-private-teams-no-longer-discoverable-in-search-or-directory/

### CODE REVIEW

**Review by dariomws — COMMENTED** [review]
Agree with @get-itips.

The same update also must be applied to New-Team article.

Thank you!

**Comment by yogkumgit** [comment]
@dilip-2201 Please review the suggested changes and update the PR

**Comment by yogkumgit** [comment]
@dilip-2201 Gentle reminder, please update the PR with suggestions. Thanks

**Comment by yogkumgit** [comment]
@get-itips and @dariomws

**Comment by dariomws** [comment]
Hi @chrisda,

This parameter is still available in the latest version (2.3.1), so I think we should leave it there with a description like "The parameter has been deprecated", as @get-itips suggested.

**Comment by chrisda** [comment]
@dariomws, I did what you suggested.

**Pull request merged**
