### PR TITLE
Update Connect-MicrosoftTeams.md

### PR DESCRIPTION
**Pull request by shriya999**
Removing service principal related updates

### CODE REVIEW

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]
@shriya999 usually, if a parameter isn't present anymore what we usually do is remove the documentation from it, agreeing on this one as many people open issues asking for them, however, we should remove them from the article in the near future I think.
Thanks

**Comment by yogkumgit** [comment]
@tseward

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by shriya999** [comment]
@get-itips thanks for the pointer ! yes this will be re-enabled back a few versions later once the functionality is fixed. So, I'm mainly making the update to indicate which versions it will be unavailable for.

**Pull request merged**
