### PR TITLE
Update Set-CsTeamsCallingPolicy.md

### PR DESCRIPTION
**Pull request by brguss**
Updated the defunct CallRecordingExpirationDays to NewCallRecordingExpirationDays

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward @get-itips @dariomws

**Comment by dariomws** [comment]
Hi @brguss,

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html 


Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=brguss

**Comment by dariomws** [comment]
@brguss, I have verified in the last GA version:

image001

**Comment by yogkumgit** [comment]
@brguss

**Comment by yogkumgit** [comment]
@brguss Gentle reminder, please add you comment. Thanks

**Comment by brguss** [comment]
> @brguss Gentle reminder, please add you comment. Thanks

@yogkumgit, I am not sure if you are just looking for confirmation that the change went through or if there is an open question. I think it looks like the change is good in production now, so that you all for the fast change. Please let me know if there are any open questions.

**Comment by get-itips** [comment]
@brguss What @yogkumgit is trying to request is that you review @dariomws comments, I also see the same, can't seem to verify on latest GA version the parameter _NewCallRecordingExpirationDays_ being present.

**Comment by brguss** [comment]
I see. I think the policy attribute is called this: "NewMeetingRecordingExpirationDays"

**Review by get-itips — COMMENTED** [review]
There is no parameter in this cmdlet starting with "-New"

**Comment by brguss** [comment]
This is what I see from other documentation, but I'm not sure who on the engineering team knows more.

https://learn.microsoft.com/en-us/microsoftteams/meetings-policies-recording-and-transcription#changing-default-expiration-time

PowerShell:

Set-CsTeamsMeetingPolicy -Identity Global -NewMeetingRecordingExpirationDays 50

**Comment by get-itips** [comment]
But that is in **Set-CsTeamsMeetingPolicy** and you opened the pull request against **Set-CsTeamsCallingPolicy**, a different cmdlet

**Comment by brguss** [comment]
Ah, sorry. Thanks for catching the mistake. Please throw out this PR in that case.

**Pull request closed without merging**
