### PR TITLE
Phone numbers updates

### PR DESCRIPTION
**Pull request by JensTrier**
Update Get-CsOnlineTelephoneNumber with GCCH and DoD replacement reference.
Update example in Complete-CsOnlineTelephoneNumberOrder

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips @dariomws @tseward

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @tseward

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Comment by yogkumgit** [comment]
@tseward Gentle reminder

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
