### PR TITLE
Remove CallerIdPolicy

### PR DESCRIPTION
**Pull request by kelqi**

### CODE REVIEW

**Comment by kenwith** [comment]
@kelqi can you provide more information on why you are trying to remove these?

**Comment by kenwith** [comment]
@islubin @tomkau - OK to remove these and merge this?

**Comment by kelqi** [comment]
> @kelqi can you provide more information on why you are trying to remove these?

It's because these were deprecated in favor of CallingLineIdentity.

**Comment by kenwith** [comment]
@kelqi - were these removed from the code though? If not, they will just show up as 'new' cmdlets next time the reflection tool is run. If they are still in code it is better to add to top of description "Deprecated in favor of CallingLineIdentity" or something to that affect. If these were removed from code then it is OK to remove them here too. @islubin or @tomkau - can you provide guidance?

**Comment by kelqi** [comment]
> @kelqi - were these removed from the code though? If not, they will just show up as 'new' cmdlets next time the reflection tool is run. If they are still in code it is better to add to top of description "Deprecated in favor of CallingLineIdentity" or something to that affect. If these were removed from code then it is OK to remove them here too. @islubin or @tomkau - can you provide guidance?

@venkat

**Comment by kelqi** [comment]
> @kelqi - were these removed from the code though? If not, they will just show up as 'new' cmdlets next time the reflection tool is run. If they are still in code it is better to add to top of description "Deprecated in favor of CallingLineIdentity" or something to that affect. If these were removed from code then it is OK to remove them here too. @islubin or @tomkau - can you provide guidance?

Venkat is working on removing this from the code, but right now it's still there.

**Comment by tomkau** [comment]
This is OK to merge.

**Pull request merged**
